# © Artur Czarnecki. All rights reserved.

"""LLM routing rules — Protocol contract and evaluator (M-LLM-X.9 · M-LLM-X.10)."""

from intergrax.llm_adapters.routing.builtin_rules import (
    AgentIdInRule,
    AlwaysRule,
    BUILTIN_ROUTING_RULE_TYPES,
    BudgetAboveRule,
    BudgetBelowRule,
    BudgetExceededDegradeRule,
    CompositeAllRule,
    CompositeAnyRule,
    ModelHintPresentRule,
    PolicyHintRule,
    StepIndexAtLeastRule,
    StepIndexBelowRule,
    TaskClassInRule,
    TaskClassNotInRule,
    TaskClassRule,
    TenantIdInRule,
    TokenThresholdRule,
    TokenUsedAboveRule,
    TokenUsedBelowRule,
    cheapest_allowed_model_hint,
)
from intergrax.llm_adapters.routing.context_bridge import (
    LLMRoutingRuntimeSnapshot,
    budget_remaining_ratio_from_limits,
    build_routing_context_from_runtime,
    refresh_llm_routing_context,
    tokens_used_from_usage,
)
from intergrax.llm_adapters.routing.contracts import (
    LLMRoutingProfile,
    LLMRoutingRule,
    LLMRoutingRuleBase,
    RoutingContext,
    RoutingEvaluation,
    RoutingHint,
    RoutingTarget,
)
from intergrax.llm_adapters.routing.evaluator import (
    AllowlistViolationError,
    LLMRoutingEvaluator,
    effective_allowlist,
    is_profile_allowed,
    profile_identity,
)

__all__ = [
    "AgentIdInRule",
    "AllowlistViolationError",
    "AlwaysRule",
    "BUILTIN_ROUTING_RULE_TYPES",
    "BudgetAboveRule",
    "BudgetBelowRule",
    "BudgetExceededDegradeRule",
    "CompositeAllRule",
    "CompositeAnyRule",
    "LLMRoutingEvaluator",
    "LLMRoutingProfile",
    "LLMRoutingRule",
    "LLMRoutingRuleBase",
    "LLMRoutingRuntimeSnapshot",
    "ModelHintPresentRule",
    "PolicyHintRule",
    "RoutingContext",
    "RoutingEvaluation",
    "RoutingHint",
    "RoutingTarget",
    "refresh_llm_routing_context",
    "StepIndexAtLeastRule",
    "StepIndexBelowRule",
    "TaskClassInRule",
    "TaskClassNotInRule",
    "TaskClassRule",
    "TenantIdInRule",
    "TokenThresholdRule",
    "TokenUsedAboveRule",
    "TokenUsedBelowRule",
    "budget_remaining_ratio_from_limits",
    "build_routing_context_from_runtime",
    "cheapest_allowed_model_hint",
    "effective_allowlist",
    "is_profile_allowed",
    "profile_identity",
    "tokens_used_from_usage",
]
