# © Artur Czarnecki. All rights reserved.

from intergrax.core.plugins.discovery import (
    EP_INTEGRATIONS,
    EP_POLICY_RULES,
    EP_SECURITY_DEFENSES,
    EP_SKILLS,
    EP_TOOL_INVOCATION_PATTERNS,
    EP_TOOLS,
    ConflictPolicy,
    EntryPointLoadResult,
    EntryPointSpec,
    LoadedPlugin,
    LoadIsolation,
    instantiate_entry_point_target,
    iter_entry_point_specs,
    load_entry_point_plugins,
    load_entry_point_targets,
    load_entry_point_value,
    load_plugin_types,
    register_plugins,
)
from intergrax.core.plugins.errors import (
    InvalidPlatformVersionError,
    PlatformIncompatibilityError,
    PlatformPluginContractError,
    PlatformPluginManifestValidationError,
    PluginConflictError,
    PluginError,
    PluginLoadError,
)
from intergrax.core.plugins.manifest_io import (
    parse_platform_plugin_manifest_data,
    parse_platform_plugin_pyproject,
    parse_platform_plugin_pyproject_toml,
)
from intergrax.core.plugins.package_contract import (
    MANIFEST_SCHEMA_VERSION,
    CapabilityDescriptor,
    PlatformCompatibility,
    PlatformPluginManifest,
    PluginPackageIdentity,
    build_platform_plugin_manifest,
)

from intergrax.core.plugins.platform_semantics import (
    PlatformCompatibilityReason,
    PlatformCompatibilityResult,
    PlatformPluginConflictKind,
    PlatformPluginLifecycleState,
    check_manifest_platform_compatibility,
    check_platform_compatibility,
    normalize_platform_version,
    package_identities_conflict,
    require_platform_compatibility,
)

__all__ = [
    "CapabilityDescriptor",
    "ConflictPolicy",
    "EntryPointLoadResult",
    "EntryPointSpec",
    "EP_INTEGRATIONS",
    "EP_POLICY_RULES",
    "EP_SECURITY_DEFENSES",
    "EP_SKILLS",
    "EP_TOOL_INVOCATION_PATTERNS",
    "EP_TOOLS",
    "InvalidPlatformVersionError",
    "LoadedPlugin",
    "LoadIsolation",
    "MANIFEST_SCHEMA_VERSION",
    "PlatformCompatibility",
    "PlatformCompatibilityReason",
    "PlatformCompatibilityResult",
    "PlatformIncompatibilityError",
    "PlatformPluginConflictKind",
    "PlatformPluginContractError",
    "PlatformPluginLifecycleState",
    "PlatformPluginManifest",
    "PlatformPluginManifestValidationError",
    "PluginConflictError",
    "PluginError",
    "PluginLoadError",
    "PluginPackageIdentity",
    "build_platform_plugin_manifest",
    "check_manifest_platform_compatibility",
    "check_platform_compatibility",
    "instantiate_entry_point_target",
    "iter_entry_point_specs",
    "load_entry_point_plugins",
    "load_entry_point_targets",
    "load_entry_point_value",
    "load_plugin_types",
    "normalize_platform_version",
    "package_identities_conflict",
    "parse_platform_plugin_manifest_data",
    "parse_platform_plugin_pyproject",
    "parse_platform_plugin_pyproject_toml",
    "register_plugins",
    "require_platform_compatibility",
]
