# © Artur Czarnecki. All rights reserved.
# Intergrax framework – proprietary and confidential.

"""Vendor-neutral platform problem/error signal contract (OBS-PROBLEM-1)."""

from __future__ import annotations

from intergrax.contracts.platform_problem_signal import (
    PLATFORM_PROBLEM_SIGNAL_SCHEMA,
    PROBLEM_KIND_PLATFORM_APPLICATION_FAILURE,
    PROBLEM_KIND_PLATFORM_ARTIFACT_FAILURE,
    PROBLEM_KIND_PLATFORM_CONFIGURATION_ERROR,
    PROBLEM_KIND_PLATFORM_EXCEPTION,
    PROBLEM_KIND_PLATFORM_EXTERNAL_EFFECT_RELIABILITY,
    PROBLEM_KIND_PLATFORM_FUNCTIONAL_OUTCOME_INVALID,
    PROBLEM_KIND_PLATFORM_INTEGRATION_FAILURE,
    PROBLEM_KIND_PLATFORM_OBSERVABILITY_EXPORT_FAILURE,
    PROBLEM_KIND_PLATFORM_POLICY_VIOLATION,
    PROBLEM_KIND_PLATFORM_RAG_FAILURE,
    PROBLEM_KIND_PLATFORM_TOOL_FAILURE,
    PROBLEM_KIND_PLATFORM_UNEXPECTED_STATE,
    PROBLEM_SEVERITY_CRITICAL,
    PROBLEM_SEVERITY_ERROR,
    PROBLEM_SEVERITY_INFO,
    PROBLEM_SEVERITY_WARNING,
    PROBLEM_SOURCE_LAYER_AGENT,
    PROBLEM_SOURCE_LAYER_APPLICATION,
    PROBLEM_SOURCE_LAYER_INTEGRATION,
    PROBLEM_SOURCE_LAYER_OBSERVABILITY,
    PROBLEM_SOURCE_LAYER_POLICY,
    PROBLEM_SOURCE_LAYER_RAG,
    PROBLEM_SOURCE_LAYER_RUNTIME,
    PROBLEM_SOURCE_LAYER_TOOL,
    PROBLEM_SOURCE_LAYER_VALIDATION,
    PROBLEM_STATUS_DETECTED,
    PROBLEM_STATUS_IGNORED,
    PROBLEM_STATUS_RESOLVED,
    PlatformProblemSignal,
)
from intergrax.runtime.observability.export_boundary import (
    FORBIDDEN_EXPORT_CONTENT_FIELDS,
)

__all__ = [
    "PLATFORM_PROBLEM_SIGNAL_SCHEMA",
    "PROBLEM_KIND_PLATFORM_APPLICATION_FAILURE",
    "PROBLEM_KIND_PLATFORM_ARTIFACT_FAILURE",
    "PROBLEM_KIND_PLATFORM_CONFIGURATION_ERROR",
    "PROBLEM_KIND_PLATFORM_EXCEPTION",
    "PROBLEM_KIND_PLATFORM_EXTERNAL_EFFECT_RELIABILITY",
    "PROBLEM_KIND_PLATFORM_FUNCTIONAL_OUTCOME_INVALID",
    "PROBLEM_KIND_PLATFORM_INTEGRATION_FAILURE",
    "PROBLEM_KIND_PLATFORM_OBSERVABILITY_EXPORT_FAILURE",
    "PROBLEM_KIND_PLATFORM_POLICY_VIOLATION",
    "PROBLEM_KIND_PLATFORM_RAG_FAILURE",
    "PROBLEM_KIND_PLATFORM_TOOL_FAILURE",
    "PROBLEM_KIND_PLATFORM_UNEXPECTED_STATE",
    "PROBLEM_SEVERITY_CRITICAL",
    "PROBLEM_SEVERITY_ERROR",
    "PROBLEM_SEVERITY_INFO",
    "PROBLEM_SEVERITY_WARNING",
    "PROBLEM_SOURCE_LAYER_AGENT",
    "PROBLEM_SOURCE_LAYER_APPLICATION",
    "PROBLEM_SOURCE_LAYER_INTEGRATION",
    "PROBLEM_SOURCE_LAYER_OBSERVABILITY",
    "PROBLEM_SOURCE_LAYER_POLICY",
    "PROBLEM_SOURCE_LAYER_RAG",
    "PROBLEM_SOURCE_LAYER_RUNTIME",
    "PROBLEM_SOURCE_LAYER_TOOL",
    "PROBLEM_SOURCE_LAYER_VALIDATION",
    "PROBLEM_STATUS_DETECTED",
    "PROBLEM_STATUS_IGNORED",
    "PROBLEM_STATUS_RESOLVED",
    "PlatformProblemSignal",
    "problem_signal_is_content_safe",
]


def _problem_signal_json_is_content_safe(serialized: str) -> bool:
    """Return False when serialized JSON exposes forbidden raw-content field names."""
    for key in FORBIDDEN_EXPORT_CONTENT_FIELDS:
        if f'"{key}"' in serialized:
            return False
    return True


def problem_signal_is_content_safe(signal: PlatformProblemSignal) -> bool:
    """Return False when serialized problem signal exposes forbidden raw-content field names."""
    return _problem_signal_json_is_content_safe(signal.model_dump_json())
