# © Artur Czarnecki. All rights reserved.

"""Phase V architecture hardening contracts and report builders."""

from intergrax.runtime.architecture.agent_certification import (
    AgentCertificationEvidence,
    AgentCertificationEvaluation,
    AgentCertificationGate,
    AgentCertificationOwner,
    GateCheckStatus,
    evaluate_agent_certification,
)
from intergrax.runtime.architecture.agent_promotion import (
    PromotionDecision,
    PromotionEvidenceBundle,
    PromotionStage,
    evaluate_agent_promotion,
)
from intergrax.runtime.architecture.agent_lifecycle_governance import (
    AgentLifecycleDecision,
    AgentLifecycleState,
    AgentLifecycleTransitionRequest,
    compute_deprecation_deadline,
    evaluate_agent_lifecycle_transition,
)
from intergrax.runtime.architecture.architecture_metrics import (
    ArchitectureMetricThresholds,
    ArchitectureMetricsReport,
    ArchitectureMetricsSummary,
    compute_architecture_metrics,
)
from intergrax.runtime.architecture.architecture_metrics_pipeline import (
    ArchitectureMetricsGateResult,
    ArchitectureMetricsPipelineReport,
    ArchitectureMetricsSnapshot,
    ArchitectureMetricsTrend,
    MetricsTrendDirection,
    build_metrics_pipeline_report,
)
from intergrax.runtime.architecture.architecture_coverage import (
    ArchitectureCoverageReport,
    ArchitectureCoverageSummary,
    compute_architecture_coverage,
)
from intergrax.runtime.architecture.debt_governance import (
    ArchitectureDebtGovernanceReport,
    ArchitectureDebtReviewPolicy,
    ArchitectureDebtReviewResult,
    DebtReviewCadence,
    evaluate_architecture_debt_governance,
)
from intergrax.runtime.architecture.capability_graph import (
    CapabilityEdge,
    CapabilityEdgeType,
    CapabilityGraph,
    CapabilityGraphVersion,
    CapabilityNode,
    CapabilityNodeType,
    build_catalog_capability_graph,
)
from intergrax.runtime.architecture.capability_graph_compatibility import (
    CapabilityCompatibilityReport,
    CompatibilityIssue,
    CompatibilitySeverity,
    evaluate_capability_graph_compatibility,
)
from intergrax.runtime.architecture.capability_graph_lineage import (
    CapabilityImpactRecord,
    CapabilityImpactReport,
    CapabilityLineageRecord,
    CapabilityLineageReport,
    build_capability_impact_report,
    build_capability_lineage_report,
)
from intergrax.runtime.architecture.evaluation_modes import (
    EvaluationMode,
    EvaluationModeRequest,
    EvaluationModeResult,
    UnifiedEvaluationReport,
)
from intergrax.runtime.architecture.evaluation_automation import (
    AutomatedEvaluationRecord,
    AutomatedEvaluationReport,
    AutomatedEvaluatorResult,
    EvaluationSignal,
    EvaluatorType,
    evaluate_automated_results,
)
from intergrax.runtime.architecture.evaluation_assets import (
    EvaluationAssetBundle,
    GoldenDatasetAsset,
    ScenarioCase,
    ScenarioLibraryAsset,
)
from intergrax.runtime.architecture.evaluation_registry_trends import (
    EvaluationComparisonSummary,
    EvaluationRegistryTrendReport,
    EvaluationReleaseSnapshot,
    build_evaluation_registry_trend_report,
)
from intergrax.runtime.architecture.production_ownership import (
    ProductionOwnerMetadata,
    ProductionOwnershipDecision,
    ProductionOwnershipEvidence,
    evaluate_production_ownership,
)
from intergrax.runtime.architecture.prompt_security import (
    PromptDefenseProfile,
    PromptInjectionRule,
    PromptInspectionResult,
    PromptRiskLevel,
    inspect_prompt_for_injection,
)
from intergrax.runtime.architecture.tool_security import (
    ToolInvocationDecision,
    ToolInvocationPolicy,
    ToolInvocationRequest,
    evaluate_tool_invocation_security,
)
from intergrax.runtime.architecture.retrieval_security import (
    RetrievalDocumentSignal,
    RetrievalPoisoningDecision,
    RetrievalPoisoningReport,
    RetrievalTrustLevel,
    evaluate_retrieval_poisoning,
)
from intergrax.runtime.architecture.tenant_security import (
    SecurityAuditEvent,
    TenantIsolationCheck,
    TenantSecurityVerificationReport,
    verify_tenant_security,
)
from intergrax.runtime.architecture.cost_budget import (
    BudgetEnvelope,
    BudgetEnvelopeDecision,
    BudgetGovernanceReport,
    BudgetScope,
    evaluate_budget_envelopes,
)
from intergrax.runtime.architecture.cost_quota import (
    QuotaEnforcementAction,
    QuotaEnforcementDecision,
    QuotaGovernanceReport,
    QuotaResourceType,
    QuotaUsageRequest,
    ResourceQuota,
    evaluate_quota_enforcement,
)
from intergrax.runtime.architecture.cost_forecast import (
    CostAnomalyRecord,
    CostAnomalySeverity,
    CostForecastPoint,
    CostForecastReport,
    CostUsageSnapshot,
    build_cost_forecast_report,
)
from intergrax.runtime.architecture.cost_optimization import (
    CostOptimizationReport,
    OptimizationGuardrail,
    OptimizationRecommendation,
    OptimizationRecommendationType,
    build_cost_optimization_report,
)

__all__ = [
    "AgentCertificationEvidence",
    "AgentCertificationEvaluation",
    "AgentCertificationGate",
    "AgentCertificationOwner",
    "AgentLifecycleDecision",
    "AgentLifecycleState",
    "AgentLifecycleTransitionRequest",
    "PromotionDecision",
    "PromotionEvidenceBundle",
    "PromotionStage",
    "ArchitectureMetricThresholds",
    "ArchitectureMetricsGateResult",
    "ArchitectureMetricsPipelineReport",
    "ArchitectureMetricsSnapshot",
    "ArchitectureMetricsReport",
    "ArchitectureMetricsSummary",
    "ArchitectureMetricsTrend",
    "ArchitectureCoverageReport",
    "ArchitectureCoverageSummary",
    "ArchitectureDebtGovernanceReport",
    "ArchitectureDebtReviewPolicy",
    "ArchitectureDebtReviewResult",
    "CapabilityEdge",
    "CapabilityEdgeType",
    "CapabilityGraph",
    "CapabilityGraphVersion",
    "CapabilityCompatibilityReport",
    "CapabilityImpactRecord",
    "CapabilityImpactReport",
    "CapabilityLineageRecord",
    "CapabilityLineageReport",
    "CapabilityNode",
    "CapabilityNodeType",
    "CompatibilityIssue",
    "CompatibilitySeverity",
    "GateCheckStatus",
    "MetricsTrendDirection",
    "EvaluationMode",
    "EvaluationModeRequest",
    "EvaluationModeResult",
    "AutomatedEvaluationRecord",
    "AutomatedEvaluationReport",
    "AutomatedEvaluatorResult",
    "EvaluationSignal",
    "EvaluatorType",
    "DebtReviewCadence",
    "EvaluationAssetBundle",
    "EvaluationComparisonSummary",
    "EvaluationRegistryTrendReport",
    "EvaluationReleaseSnapshot",
    "GoldenDatasetAsset",
    "ScenarioCase",
    "ScenarioLibraryAsset",
    "ProductionOwnerMetadata",
    "ProductionOwnershipDecision",
    "ProductionOwnershipEvidence",
    "PromptDefenseProfile",
    "PromptInjectionRule",
    "PromptInspectionResult",
    "PromptRiskLevel",
    "ToolInvocationDecision",
    "ToolInvocationPolicy",
    "ToolInvocationRequest",
    "RetrievalDocumentSignal",
    "RetrievalPoisoningDecision",
    "RetrievalPoisoningReport",
    "RetrievalTrustLevel",
    "SecurityAuditEvent",
    "TenantIsolationCheck",
    "TenantSecurityVerificationReport",
    "BudgetEnvelope",
    "BudgetEnvelopeDecision",
    "BudgetGovernanceReport",
    "BudgetScope",
    "QuotaEnforcementAction",
    "QuotaEnforcementDecision",
    "QuotaGovernanceReport",
    "QuotaResourceType",
    "QuotaUsageRequest",
    "ResourceQuota",
    "CostAnomalyRecord",
    "CostAnomalySeverity",
    "CostForecastPoint",
    "CostForecastReport",
    "CostUsageSnapshot",
    "CostOptimizationReport",
    "OptimizationGuardrail",
    "OptimizationRecommendation",
    "OptimizationRecommendationType",
    "UnifiedEvaluationReport",
    "evaluate_agent_certification",
    "evaluate_agent_lifecycle_transition",
    "evaluate_agent_promotion",
    "evaluate_production_ownership",
    "inspect_prompt_for_injection",
    "evaluate_tool_invocation_security",
    "evaluate_retrieval_poisoning",
    "verify_tenant_security",
    "evaluate_budget_envelopes",
    "evaluate_quota_enforcement",
    "build_cost_forecast_report",
    "build_cost_optimization_report",
    "build_catalog_capability_graph",
    "build_capability_impact_report",
    "build_capability_lineage_report",
    "compute_architecture_metrics",
    "build_metrics_pipeline_report",
    "compute_architecture_coverage",
    "evaluate_architecture_debt_governance",
    "compute_deprecation_deadline",
    "evaluate_capability_graph_compatibility",
    "evaluate_automated_results",
    "build_evaluation_registry_trend_report",
]
