# © Artur Czarnecki. All rights reserved.
# Intergrax framework – proprietary and confidential.

"""Compatibility re-export — canonical: intergrax.contracts.task_metadata_keys."""

from __future__ import annotations

from intergrax.contracts.task_metadata_keys import (
    CHECKPOINT_ID_KEY,
    ESCALATION_CHAIN_KEY,
    ESCALATION_LEVEL_KEY,
    ESCALATION_TARGET_KEY,
    GOVERNANCE_HUMAN_REQUEST_KEY,
    GOVERNANCE_INTERRUPT_KEY,
    GOVERNANCE_PAUSE_KEY,
    GOVERNANCE_PAUSE_RECORD_KEY,
    HUMAN_APPROVED_KEY,
    HUMAN_DECISION_KEY,
    HUMAN_ESCALATED_KEY,
    HUMAN_REJECTED_KEY,
    HUMAN_REQUEST_CREATED_AT_KEY,
    HUMAN_REQUEST_EXPIRES_AT_KEY,
    HUMAN_RESPONSE_KEY,
    LONG_RUNNING_CHECKPOINT_ON_PAUSE_KEY,
    LONG_RUNNING_FLAG,
    LONG_RUNNING_NOTIFY_CHANNEL_KEY,
    PROGRESS_MESSAGE_KEY,
    RESUME_TOKEN_KEY,
    SHARED_TASK_CONTEXT_KEY,
    TASK_METADATA_LEGACY_OPTION_KEYS,
    TASK_METADATA_LEGACY_RUNTIME_KEYS,
    TaskMetadataKey,
    TaskOrchestrationMetadataKey,
    TaskResultMetadataKey,
)

__all__ = [
    "CHECKPOINT_ID_KEY",
    "ESCALATION_CHAIN_KEY",
    "ESCALATION_LEVEL_KEY",
    "ESCALATION_TARGET_KEY",
    "GOVERNANCE_HUMAN_REQUEST_KEY",
    "GOVERNANCE_INTERRUPT_KEY",
    "GOVERNANCE_PAUSE_KEY",
    "GOVERNANCE_PAUSE_RECORD_KEY",
    "HUMAN_APPROVED_KEY",
    "HUMAN_DECISION_KEY",
    "HUMAN_ESCALATED_KEY",
    "HUMAN_REJECTED_KEY",
    "HUMAN_REQUEST_CREATED_AT_KEY",
    "HUMAN_REQUEST_EXPIRES_AT_KEY",
    "HUMAN_RESPONSE_KEY",
    "LONG_RUNNING_CHECKPOINT_ON_PAUSE_KEY",
    "LONG_RUNNING_FLAG",
    "LONG_RUNNING_NOTIFY_CHANNEL_KEY",
    "PROGRESS_MESSAGE_KEY",
    "RESUME_TOKEN_KEY",
    "SHARED_TASK_CONTEXT_KEY",
    "TASK_METADATA_LEGACY_OPTION_KEYS",
    "TASK_METADATA_LEGACY_RUNTIME_KEYS",
    "TaskMetadataKey",
    "TaskOrchestrationMetadataKey",
    "TaskResultMetadataKey",
]
