# © Artur Czarnecki. All rights reserved.
# Intergrax framework – proprietary and confidential.

"""Legacy flat metadata keys for task bridge compatibility."""

GOVERNANCE_HUMAN_REQUEST_KEY = "governance_human_request"
GOVERNANCE_INTERRUPT_KEY = "governance_interrupt"
GOVERNANCE_PAUSE_KEY = "governance_pause"
GOVERNANCE_PAUSE_RECORD_KEY = "governance_pause_record"
HUMAN_APPROVED_KEY = "human_approved"
HUMAN_DECISION_KEY = "human_decision"
HUMAN_ESCALATED_KEY = "human_escalated"
HUMAN_REJECTED_KEY = "human_rejected"
HUMAN_RESPONSE_KEY = "human_response"
HUMAN_REQUEST_CREATED_AT_KEY = "human_request_created_at"
HUMAN_REQUEST_EXPIRES_AT_KEY = "human_request_expires_at"
ESCALATION_CHAIN_KEY = "escalation_chain"
ESCALATION_LEVEL_KEY = "escalation_level"
ESCALATION_TARGET_KEY = "escalation_target"
LONG_RUNNING_FLAG = "long_running"
LONG_RUNNING_NOTIFY_CHANNEL_KEY = "long_running_notify_channel"
LONG_RUNNING_CHECKPOINT_ON_PAUSE_KEY = "long_running_checkpoint_on_pause"
RESUME_TOKEN_KEY = "resume_token"
CHECKPOINT_ID_KEY = "checkpoint_id"
PROGRESS_MESSAGE_KEY = "progress_message"
