"""Arena outcome and gate classification."""

from __future__ import annotations

from enum import Enum


class EmbeddingLicenseClassification(str, Enum):
    ELIGIBLE_COMMERCIAL = "ELIGIBLE_COMMERCIAL"
    RESEARCH_ONLY = "RESEARCH_ONLY"
    UNKNOWN = "UNKNOWN"
    REJECTED = "REJECTED"


class EmbeddingArenaCandidateEligibility(str, Enum):
    ELIGIBLE = "ELIGIBLE"
    BLOCKED_LICENSE = "BLOCKED_LICENSE"
    BLOCKED_RUNTIME = "BLOCKED_RUNTIME"
    OPTIONAL_CONTROL = "OPTIONAL_CONTROL"


class EmbeddingArenaStageStatus(str, Enum):
    NOT_RUN = "NOT_RUN"
    PASS = "PASS"
    FAILED_CORRECTNESS = "FAILED_CORRECTNESS"
    FAILED_OOM = "FAILED_OOM"
    FAILED_RUNTIME = "FAILED_RUNTIME"
    FAILED_RUNTIME_BUDGET = "FAILED_RUNTIME_BUDGET"
    SKIPPED = "SKIPPED"


class MicroArenaScreeningOutcome(str, Enum):
    PROMISING = "PROMISING"
    NOT_PROMISING = "NOT_PROMISING"
    RUNTIME_REJECTED = "RUNTIME_REJECTED"
    QUALITY_CONCERN = "QUALITY_CONCERN"
    MORE_EVIDENCE_REQUIRED = "MORE_EVIDENCE_REQUIRED"


class ArenaEvidenceClassification(str, Enum):
    FINAL_MODEL_QUALITY = "FINAL_MODEL_QUALITY"
    FINALIST_QUALIFICATION = "FINALIST_QUALIFICATION"
    MICRO_ARENA_SCREENING = "MICRO_ARENA_SCREENING"
    NANO_ARENA_SCREENING = "NANO_ARENA_SCREENING"


class FinalistQualificationGate(str, Enum):
    BASELINE_CLEAR_WIN = "BASELINE_CLEAR_WIN"
    CHALLENGER_CLEAR_WIN = "CHALLENGER_CLEAR_WIN"
    AMBIGUOUS = "AMBIGUOUS"
    RUNTIME_REJECTED = "RUNTIME_REJECTED"
    QUALITY_REGRESSION = "QUALITY_REGRESSION"
    MORE_EVIDENCE_REQUIRED = "MORE_EVIDENCE_REQUIRED"


class EmbeddingArenaVerdict(str, Enum):
    BASELINE = "BASELINE"
    REJECTED_CORRECTNESS = "REJECTED_CORRECTNESS"
    REJECTED_LICENSE = "REJECTED_LICENSE"
    REJECTED_QUALITY = "REJECTED_QUALITY"
    REJECTED_RUNTIME = "REJECTED_RUNTIME"
    QUALIFIED = "QUALIFIED"
    QUALIFIED_TRADEOFF = "QUALIFIED_TRADEOFF"
    WINNER_CANDIDATE = "WINNER_CANDIDATE"


class EmbeddingArenaDecision(str, Enum):
    KEEP_BGE_M3 = "KEEP_BGE_M3"
    PROMOTE_QWEN3_0_6B_CANDIDATE = "PROMOTE_QWEN3_0_6B_CANDIDATE"
    PROMOTE_NOMIC_V2_CANDIDATE = "PROMOTE_NOMIC_V2_CANDIDATE"
    PROMOTE_E5_INSTRUCT_CANDIDATE = "PROMOTE_E5_INSTRUCT_CANDIDATE"
    NO_CLEAR_WINNER = "NO_CLEAR_WINNER"
    MORE_EVIDENCE_REQUIRED = "MORE_EVIDENCE_REQUIRED"


class QueryDifficultyClass(str, Enum):
    STRONG_IDENTITY = "STRONG_IDENTITY"
    TITLE_BRAND = "TITLE_BRAND"
    TITLE_ONLY = "TITLE_ONLY"
    STRUCTURED_ATTRIBUTES = "STRUCTURED_ATTRIBUTES"
    PARTIAL_NOISY = "PARTIAL_NOISY"
    LONG_DESCRIPTION_SIGNAL = "LONG_DESCRIPTION_SIGNAL"


class SpeedupBand(str, Enum):
    UNDER_1_5X = "UNDER_1_5X"
    BAND_1_5_TO_2X = "BAND_1_5_TO_2X"
    BAND_2_TO_4X = "BAND_2_TO_4X"
    OVER_4X = "OVER_4X"
