# © Artur Czarnecki. All rights reserved.
# Intergrax framework – proprietary and confidential.

"""Tier-0 Agent Distribution domain contracts, stores, and services (AP-3/AP-4)."""

from intergrax.agent_distribution.agent_capability_metadata import (
    AgentCapabilityDescriptor,
    AgentCapabilityDescriptorConflictError,
    AgentCapabilityMetadataProvider,
    merge_agent_capability_descriptors,
)
from intergrax.agent_distribution.agent_project_metadata import (
    AgentProjectMetadata,
    AgentProjectMetadataProvider,
)
from intergrax.agent_distribution.builtin_capability_metadata import (
    BuiltinAgentCapabilityMetadataProvider,
    default_agent_capability_metadata_provider,
)
from intergrax.agent_distribution.binding import (
    AgentBindingFactoryReference,
    AgentBindingPolicyOverrides,
    ApplicationAgentBinding,
)
from intergrax.agent_distribution.admin_models import (
    ActivateRuntimeRevisionRequest,
    AgentPlatformAdminBlockedError,
    AgentStatusView,
    BindAgentRequest,
    BuildApplicationRevisionRequest,
    InstallAgentRequest,
    RollbackRuntimeRevisionRequest,
    SetAgentEnablementRequest,
    UpdateAgentBindingRequest,
)
from intergrax.agent_distribution.admin_service import AgentPlatformAdminService
from intergrax.agent_distribution.binding_service import BindingService
from intergrax.agent_distribution.catalog import (
    AgentCatalogEntry,
    AgentCatalogVersionChannelRef,
    CatalogEntryFilters,
    CatalogPackageResolution,
    CatalogProviderKind,
    CatalogSourceIdentity,
    CatalogSourceProvider,
    ProviderHealth,
    ProviderHealthStatus,
)
from intergrax.agent_distribution.dependency import (
    CandidateDependencySpecification,
    DependencyResolverInput,
    InstalledAgentPackageRequirement,
    InstalledAgentRequirementSet,
    MaterializedAgentClosureEntry,
    MaterializedLockPackage,
    MaterializedLockReproducibilityEvidence,
    MaterializedLockRollbackEvidence,
    MaterializedRuntimeLock,
    PolicyDependencyConstraint,
    RepositoryDependencyDeclaration,
)
from intergrax.agent_distribution.dependency_specification import (
    build_candidate_dependency_specification,
)
from intergrax.agent_distribution.effective_roster import (
    EffectiveRosterBuilder,
    InstalledAgentRequirementSetBuilder,
)
from intergrax.agent_distribution.errors import (
    AgentDistributionError,
    AgentDistributionNotFoundError,
    AgentPackageTrustError,
    BindingLifecycleError,
    BindingRevisionConflict,
    DependencySpecificationError,
    DependencyResolutionError,
    EffectiveRosterConflict,
    InstallationLifecycleError,
    InstallationSlotConflict,
    MaterializedRuntimeLockConflict,
    MaterializedRuntimeLockError,
    MaterializationError,
    MaterializationInputConflict,
    MaterializationUnsupportedTopology,
    CandidateRuntimeGraphError,
    RuntimeActivationConflict,
    RuntimeActivationError,
    RuntimeDrainError,
    RuntimeReadinessError,
    RuntimeRevisionConflict,
    RuntimeRevisionLifecycleError,
    RuntimeRollbackError,
)
from intergrax.agent_distribution.events import AgentDistributionEvent, TransitionResult
from intergrax.agent_distribution.in_memory_stores import (
    AgentDistributionStoreState,
    InMemoryAgentArtifactMetadataStore,
    InMemoryAgentInstallationStore,
    InMemoryApplicationAgentBindingStore,
    InMemoryApplicationEnvironmentActivationStore,
    InMemoryApplicationEnvironmentServingStore,
    InMemoryDeploymentInstanceStore,
    InMemoryMaterializedRuntimeLockStore,
    InMemoryRuntimeRevisionStore,
)
from intergrax.agent_distribution.installation_service import InstallationService
from intergrax.agent_distribution.installation import (
    AgentInstallationRecord,
    InstallationState,
    installation_state_is_installed,
)
from intergrax.agent_distribution.package_trust import (
    AgentPackageTrustCoordinator,
    assert_installation_trust_record_acceptable,
)
from intergrax.agent_distribution.activation import (
    ActivationCommitResult,
    ActivationService,
    ArtifactRevalidationHook,
    DrainCompletionResult,
    FakeRuntimeServingProjectionCoordinator,
    RollbackResult,
    RuntimeServingProjectionCoordinator,
)
from intergrax.agent_distribution.deployment import (
    DeploymentInstanceRecord,
    DeploymentInstanceState,
    DrainActionOnTimeout,
    DrainPolicy,
    DrainStatus,
    FakeInMemoryRuntimeDeploymentAdapter,
    PreparedDeployment,
    RuntimeDeploymentAdapter,
)
from intergrax.agent_distribution.materialization import (
    ApplicationBuildContext,
    MaterializationInput,
    MaterializationOutput,
)
from intergrax.agent_distribution.materialization_adapters import (
    FakeRuntimeMaterializationAdapter,
    OciImageMaterializationAdapter,
    RuntimeMaterializationAdapter,
    UnsupportedVenvBundleMaterializationAdapter,
    default_materialization_adapters,
)
from intergrax.agent_distribution.materialization_service import RuntimeMaterializationService
from intergrax.agent_distribution.roster import (
    EffectiveRoster,
    EffectiveRosterEntry,
    ManifestDefaultAgentDeclaration,
)
from intergrax.agent_distribution.runtime_graph import (
    CandidateApplicationRuntimeGraph,
    RuntimeGraphAgentRef,
    RuntimeGraphThirdPartyRef,
    RuntimeGraphTierViolation,
)
from intergrax.agent_distribution.identity import (
    AgentPackageCandidate,
    AgentPackageIdentity,
)
from intergrax.agent_distribution.runtime_revision import (
    MaterializationTopology,
    RuntimeRevision,
    RuntimeRevisionState,
)
from intergrax.agent_distribution.resolver import (
    CallableDependencyResolver,
    DependencyResolver,
    ResolvedDependencyClosure,
)
from intergrax.agent_distribution.runtime_graph_service import (
    CandidateRuntimeGraphBuilder,
    CandidateRuntimeGraphValidator,
)
from intergrax.agent_distribution.runtime_lock import (
    MaterializedRuntimeLockProducer,
    MaterializedRuntimeLockService,
)
from intergrax.agent_distribution.runtime_revision_service import RuntimeRevisionService
from intergrax.agent_distribution.stores import (
    ActivationAtomicCommitResult,
    AgentArtifactMetadata,
    AgentArtifactMetadataStore,
    AgentInstallationStore,
    ApplicationAgentBindingStore,
    ApplicationEnvironmentActivationStore,
    ApplicationEnvironmentServingRecord,
    ApplicationEnvironmentServingStore,
    DeploymentInstanceStore,
    MaterializedRuntimeLockStore,
    RollbackAtomicCommitResult,
    RuntimeRevisionStore,
)
from intergrax.agent_distribution.trust import (
    AgentDeliverySource,
    AgentInstallationTrustRecord,
    AgentPackageQualificationResult,
    AgentPackageTrustDecision,
    AgentPackageTrustOutcome,
    AgentPackageTrustPolicy,
    AgentPackageTrustPosture,
    AgentPackageTrustReasonCode,
    AgentPackageTrustRevocationState,
    AgentPublisherIdentity,
    AgentQualificationEvidenceKind,
    AgentTrustEvidenceRef,
)

__all__ = [
    "ActivationAtomicCommitResult",
    "ActivationCommitResult",
    "ActivationService",
    "ActivateRuntimeRevisionRequest",
    "AgentPlatformAdminBlockedError",
    "AgentPlatformAdminService",
    "AgentStatusView",
    "BindAgentRequest",
    "BuildApplicationRevisionRequest",
    "AgentArtifactMetadata",
    "AgentArtifactMetadataStore",
    "AgentBindingFactoryReference",
    "AgentBindingPolicyOverrides",
    "AgentCapabilityDescriptor",
    "AgentCapabilityDescriptorConflictError",
    "AgentCapabilityMetadataProvider",
    "AgentCatalogEntry",
    "AgentCatalogVersionChannelRef",
    "AgentDeliverySource",
    "AgentDistributionError",
    "AgentDistributionEvent",
    "AgentDistributionNotFoundError",
    "AgentDistributionStoreState",
    "AgentInstallationRecord",
    "AgentInstallationStore",
    "AgentInstallationTrustRecord",
    "AgentProjectMetadata",
    "AgentProjectMetadataProvider",
    "AgentPackageCandidate",
    "AgentPackageIdentity",
    "AgentPackageQualificationResult",
    "AgentPackageTrustCoordinator",
    "AgentPackageTrustDecision",
    "AgentPackageTrustError",
    "AgentPackageTrustOutcome",
    "AgentPackageTrustPolicy",
    "AgentPackageTrustPosture",
    "AgentPackageTrustReasonCode",
    "AgentPackageTrustRevocationState",
    "AgentPublisherIdentity",
    "AgentQualificationEvidenceKind",
    "AgentTrustEvidenceRef",
    "ApplicationAgentBinding",
    "ApplicationAgentBindingStore",
    "ApplicationEnvironmentActivationStore",
    "ApplicationEnvironmentServingRecord",
    "ApplicationEnvironmentServingStore",
    "ArtifactRevalidationHook",
    "BuiltinAgentCapabilityMetadataProvider",
    "BindingLifecycleError",
    "BindingRevisionConflict",
    "BindingService",
    "CallableDependencyResolver",
    "CandidateApplicationRuntimeGraph",
    "CandidateRuntimeGraphBuilder",
    "CandidateRuntimeGraphError",
    "CandidateRuntimeGraphValidator",
    "CandidateDependencySpecification",
    "CatalogEntryFilters",
    "CatalogPackageResolution",
    "CatalogProviderKind",
    "CatalogSourceIdentity",
    "CatalogSourceProvider",
    "DeploymentInstanceRecord",
    "DeploymentInstanceState",
    "DeploymentInstanceStore",
    "DrainActionOnTimeout",
    "DrainCompletionResult",
    "DrainPolicy",
    "DrainStatus",
    "InMemoryApplicationAgentBindingStore",
    "DependencySpecificationError",
    "DependencyResolutionError",
    "DependencyResolver",
    "DependencyResolverInput",
    "EffectiveRosterBuilder",
    "EffectiveRosterConflict",
    "EffectiveRoster",
    "EffectiveRosterEntry",
    "InMemoryApplicationEnvironmentActivationStore",
    "InMemoryApplicationEnvironmentServingStore",
    "InMemoryDeploymentInstanceStore",
    "InMemoryAgentInstallationStore",
    "InMemoryAgentArtifactMetadataStore",
    "InMemoryMaterializedRuntimeLockStore",
    "InMemoryRuntimeRevisionStore",
    "InstallAgentRequest",
    "InstalledAgentPackageRequirement",
    "InstalledAgentRequirementSet",
    "InstalledAgentRequirementSetBuilder",
    "InstallationLifecycleError",
    "InstallationService",
    "InstallationSlotConflict",
    "InstallationState",
    "ManifestDefaultAgentDeclaration",
    "ApplicationBuildContext",
    "MaterializationError",
    "MaterializationInputConflict",
    "MaterializationUnsupportedTopology",
    "MaterializationInput",
    "MaterializationOutput",
    "OciImageMaterializationAdapter",
    "RuntimeMaterializationAdapter",
    "RuntimeMaterializationService",
    "FakeInMemoryRuntimeDeploymentAdapter",
    "FakeRuntimeMaterializationAdapter",
    "FakeRuntimeServingProjectionCoordinator",
    "UnsupportedVenvBundleMaterializationAdapter",
    "default_agent_capability_metadata_provider",
    "default_materialization_adapters",
    "MaterializationTopology",
    "MaterializedAgentClosureEntry",
    "MaterializedLockPackage",
    "MaterializedLockReproducibilityEvidence",
    "MaterializedLockRollbackEvidence",
    "MaterializedRuntimeLock",
    "MaterializedRuntimeLockConflict",
    "MaterializedRuntimeLockError",
    "MaterializedRuntimeLockProducer",
    "MaterializedRuntimeLockService",
    "MaterializedRuntimeLockStore",
    "merge_agent_capability_descriptors",
    "merge_agent_capability_descriptors",
    "PolicyDependencyConstraint",
    "ProviderHealth",
    "ProviderHealthStatus",
    "RepositoryDependencyDeclaration",
    "ResolvedDependencyClosure",
    "PreparedDeployment",
    "RollbackAtomicCommitResult",
    "RollbackResult",
    "RollbackRuntimeRevisionRequest",
    "RuntimeActivationConflict",
    "RuntimeActivationError",
    "RuntimeDeploymentAdapter",
    "RuntimeDrainError",
    "RuntimeReadinessError",
    "RuntimeRollbackError",
    "RuntimeServingProjectionCoordinator",
    "SetAgentEnablementRequest",
    "RuntimeGraphAgentRef",
    "RuntimeGraphThirdPartyRef",
    "RuntimeGraphTierViolation",
    "RuntimeRevision",
    "RuntimeRevisionConflict",
    "RuntimeRevisionLifecycleError",
    "RuntimeRevisionService",
    "RuntimeRevisionState",
    "RuntimeRevisionStore",
    "TransitionResult",
    "UpdateAgentBindingRequest",
    "assert_installation_trust_record_acceptable",
    "build_candidate_dependency_specification",
    "installation_state_is_installed",
]
