# © Artur Czarnecki. All rights reserved.

"""Token Optimization runtime package (Phase TOKEN-1A/TOKEN-1B/TOKEN-1B-R/TOKEN-1C)."""

from __future__ import annotations

from intergrax.runtime.token_optimization.contracts import (
    CompressionLevel,
    CompressionReceiptRef,
    OutputPolicy,
    OutputProfile,
    ProtectedRegion,
    ProtectedRegionKind,
    ProtectedRegionValidationResult,
    ProtectedRegionValidationStatus,
    StrategySafetyClass,
    TokenCategory,
    TokenOptimizationAttribution,
    TokenOptimizationBypassReason,
    TokenOptimizationDecision,
    TokenOptimizationMechanism,
    TokenOptimizationPluginCapability,
    TokenOptimizationPluginDescriptor,
    TokenOptimizationPolicy,
    TokenOptimizationProfile,
    TokenOptimizationRequest,
    TokenOptimizationResult,
    TokenOptimizationSourceType,
    TokenOptimizationStrategyKind,
    TokenOptimizationStrategyRef,
    TokenSavingsClaimConfidence,
    TokenSavingsMeasurement,
    TokenUsageMeasurement,
)
from intergrax.runtime.token_optimization.receipts import (
    CompressionReceipt,
    CompressionReceiptValidationResult,
    CompressionReceiptValidationStatus,
    build_compression_receipt,
    hash_content,
    make_compression_receipt_ref,
    validate_receipt_integrity,
)
from intergrax.runtime.token_optimization.protected_regions import (
    BUILT_IN_PROTECTED_TERMS,
    MAX_ENV_PROTECTED_TERMS,
    MAX_PROTECTED_TERM_LENGTH,
    PROTECTED_TERMS_ENV_VAR,
    detect_protected_regions,
    get_env_protected_terms,
    parse_protected_terms,
    resolve_protected_terms,
    validate_protected_regions,
)

__all__ = [
    "build_compression_receipt",
    "BUILT_IN_PROTECTED_TERMS",
    "CompressionLevel",
    "CompressionReceipt",
    "CompressionReceiptRef",
    "CompressionReceiptValidationResult",
    "CompressionReceiptValidationStatus",
    "MAX_ENV_PROTECTED_TERMS",
    "MAX_PROTECTED_TERM_LENGTH",
    "PROTECTED_TERMS_ENV_VAR",
    "detect_protected_regions",
    "hash_content",
    "get_env_protected_terms",
    "make_compression_receipt_ref",
    "parse_protected_terms",
    "resolve_protected_terms",
    "OutputPolicy",
    "OutputProfile",
    "ProtectedRegion",
    "ProtectedRegionKind",
    "ProtectedRegionValidationResult",
    "ProtectedRegionValidationStatus",
    "StrategySafetyClass",
    "TokenCategory",
    "TokenOptimizationAttribution",
    "TokenOptimizationBypassReason",
    "TokenOptimizationDecision",
    "TokenOptimizationMechanism",
    "TokenOptimizationPluginCapability",
    "TokenOptimizationPluginDescriptor",
    "TokenOptimizationPolicy",
    "TokenOptimizationProfile",
    "TokenOptimizationRequest",
    "TokenOptimizationResult",
    "TokenOptimizationSourceType",
    "TokenOptimizationStrategyKind",
    "TokenOptimizationStrategyRef",
    "TokenSavingsClaimConfidence",
    "TokenSavingsMeasurement",
    "TokenUsageMeasurement",
    "validate_protected_regions",
    "validate_receipt_integrity",
]
