# © Artur Czarnecki. All rights reserved.
# Intergrax framework — proprietary and confidential.

"""Bounded read limits for federated runtime inspection."""

from __future__ import annotations

DEFAULT_RUNTIME_INSPECTION_TOOL_INVOCATION_LIMIT = 128
MAX_RUNTIME_INSPECTION_TOOL_INVOCATION_LIMIT = 512

DEFAULT_RUNTIME_INSPECTION_GOVERNANCE_DECISION_LIMIT = 128
MAX_RUNTIME_INSPECTION_GOVERNANCE_DECISION_LIMIT = 512

DEFAULT_RUNTIME_INSPECTION_CONTINUATION_EPISODE_LIMIT = 16
MAX_RUNTIME_INSPECTION_CONTINUATION_EPISODE_LIMIT = 64

__all__ = [
    "DEFAULT_RUNTIME_INSPECTION_CONTINUATION_EPISODE_LIMIT",
    "DEFAULT_RUNTIME_INSPECTION_GOVERNANCE_DECISION_LIMIT",
    "DEFAULT_RUNTIME_INSPECTION_TOOL_INVOCATION_LIMIT",
    "MAX_RUNTIME_INSPECTION_CONTINUATION_EPISODE_LIMIT",
    "MAX_RUNTIME_INSPECTION_GOVERNANCE_DECISION_LIMIT",
    "MAX_RUNTIME_INSPECTION_TOOL_INVOCATION_LIMIT",
]
