# © Artur Czarnecki. All rights reserved.
# Prepare minimal context, then compose:
#   uv run python scripts/build/build_application_image.py --application poc_template_application \
#     --context-dir applications/poc_template_application/docker/runtime-context --keep-context --manifest-only
#   uv run python scripts/build/build_application_image.py --application poc_template_application \
#     --tag poc_template-application:latest --context-dir applications/poc_template_application/docker/runtime-context --keep-context
# Or: docker compose -f applications/poc_template_application/docker/docker-compose.yml up --build
# (requires runtime-context/ already materialized; same isolation contract as CLI).

name: intergrax_poc_template

services:
  poc_template:
    build:
      context: ./runtime-context
      dockerfile: Dockerfile
    image: poc_template-application:latest
    ports:
      - "8095:8095"
    env_file:
      - ../.env
    environment:
      INTERGRAX_ENV: dev
      POC_TEMPLATE_BACKEND_ENV: dev
      POC_TEMPLATE_BACKEND_HOST: "0.0.0.0"
      POC_TEMPLATE_BACKEND_PORT: "8095"
      POC_TEMPLATE_INCLUDE_MCP: "false"
