# © Artur Czarnecki. All rights reserved.
# Intergrax framework – proprietary and confidential.

"""Platform integration contracts (Tier-1 runtime)."""

from intergrax.runtime.integrations.contracts import (
    PLATFORM_INTEGRATION_CONTRACT_SCHEMA,
    PlatformIntegrationCapability,
    PlatformIntegrationConfig,
    PlatformIntegrationContract,
    PlatformIntegrationHealth,
    PlatformIntegrationKind,
    PlatformIntegrationSecurityPosture,
    PlatformIntegrationStatus,
    derive_platform_integration_id,
)
from intergrax.runtime.integrations.document_store import (
    DOCUMENT_STORE_VENDOR_INTEGRATION_CONTRACT_SCHEMA,
    DocumentStoreVendorIntegrationConfig,
    DocumentStoreVendorIntegrationContract,
    DocumentStoreVendorKind,
    DocumentStoreVendorOperation,
)
from intergrax.runtime.integrations.observability import (
    OBSERVABILITY_VENDOR_INTEGRATION_CONTRACT_SCHEMA,
    OBSERVABILITY_VENDOR_PAYLOAD_SCHEMA,
    ObservabilityVendorIntegrationConfig,
    ObservabilityVendorIntegrationContract,
    ObservabilityVendorKind,
    ObservabilityVendorMappingResult,
    ObservabilityVendorPayload,
    ObservabilityVendorSignal,
    map_envelope_to_vendor_payload,
    require_policy_sanitized_envelope,
)
from intergrax.runtime.integrations.observability_otlp import (
    OTLP_OBSERVABILITY_PROVIDER_ID,
    OtlpObservabilityIntegration,
    OtlpObservabilityIntegrationConfig,
)
from intergrax.runtime.integrations.registry_v2 import (
    DuplicateIntegrationRegistrationError,
    IntegrationCapability,
    IntegrationFactory,
    IntegrationRegistration,
    IntegrationRegistry,
    IntegrationRegistryError,
    IntegrationSecurityPosture,
    MissingIntegrationRegistrationError,
    RegistrationKey,
    build_contract_registry,
    build_integration_registration,
    contract_for_category,
    expected_integration_kind_for_category,
    get_integration_registration,
    list_by_category,
    list_by_provider,
    list_integration_registrations,
    non_deferred_provider_slugs,
    register_integration,
)

__all__ = [
    "DOCUMENT_STORE_VENDOR_INTEGRATION_CONTRACT_SCHEMA",
    "DocumentStoreVendorIntegrationConfig",
    "DocumentStoreVendorIntegrationContract",
    "DocumentStoreVendorKind",
    "DocumentStoreVendorOperation",
    "DuplicateIntegrationRegistrationError",
    "IntegrationCapability",
    "IntegrationFactory",
    "IntegrationRegistration",
    "IntegrationRegistry",
    "IntegrationRegistryError",
    "IntegrationSecurityPosture",
    "MissingIntegrationRegistrationError",
    "OTLP_OBSERVABILITY_PROVIDER_ID",
    "OtlpObservabilityIntegration",
    "OtlpObservabilityIntegrationConfig",
    "OBSERVABILITY_VENDOR_INTEGRATION_CONTRACT_SCHEMA",
    "OBSERVABILITY_VENDOR_PAYLOAD_SCHEMA",
    "PLATFORM_INTEGRATION_CONTRACT_SCHEMA",
    "ObservabilityVendorIntegrationConfig",
    "ObservabilityVendorIntegrationContract",
    "ObservabilityVendorKind",
    "ObservabilityVendorMappingResult",
    "ObservabilityVendorPayload",
    "ObservabilityVendorSignal",
    "PlatformIntegrationCapability",
    "PlatformIntegrationConfig",
    "PlatformIntegrationContract",
    "PlatformIntegrationHealth",
    "PlatformIntegrationKind",
    "PlatformIntegrationSecurityPosture",
    "PlatformIntegrationStatus",
    "RegistrationKey",
    "build_contract_registry",
    "build_integration_registration",
    "contract_for_category",
    "derive_platform_integration_id",
    "expected_integration_kind_for_category",
    "get_integration_registration",
    "list_by_category",
    "list_by_provider",
    "list_integration_registrations",
    "map_envelope_to_vendor_payload",
    "non_deferred_provider_slugs",
    "register_integration",
    "require_policy_sanitized_envelope",
]
