# © Artur Czarnecki. All rights reserved.

"""Public Unified Context Lifecycle runtime contracts and serialization."""

from __future__ import annotations

from intergrax.runtime.context_lifecycle.contracts import (
    assess_durable_compaction_eligibility,
    ArtifactCompatibilityReason,
    ArtifactCompatibilityResult,
    ArtifactCompatibilityStatus,
    ArtifactCompressionTarget,
    ArtifactCreationCoordinationStatus,
    ArtifactCreationReservation,
    ArtifactLookupKey,
    ArtifactSourceRange,
    ArtifactValidationStatus,
    ArtifactValidationSummary,
    ContextOptimizationDecision,
    ContextOptimizationMode,
    ContextOptimizationPolicy,
    ContextOptimizationReasonCode,
    DurableCompactionActivationMode,
    DurableCompactionActivationRequirements,
    DurableCompactionEligibilityDecision,
    DurableCompactionEligibilityReasonCode,
    DurableCompactionPolicy,
    DurableCompactionSourceIdentity,
    DurableCompactionStabilityEvidence,
    DurableCompactionValidationRequirement,
    EphemeralArtifactPersistencePolicy,
    ModelCallExecutionScope,
    OptimizationArtifactType,
    OptimizationExecutionGuard,
    ReusableArtifactStatus,
    ReusableOptimizationArtifact,
)
from intergrax.runtime.context_lifecycle.in_memory_repository import (
    InMemoryOptimizationArtifactRepository,
)
from intergrax.runtime.context_lifecycle.sqlite_repository import (
    SQLiteOptimizationArtifactRepository,
)
from intergrax.runtime.context_lifecycle.repository import (
    ArtifactCreationCoordinationResult,
    OptimizationArtifactReference,
    OptimizationArtifactRepository,
    OptimizationArtifactRepositoryCapabilities,
    StoredOptimizationArtifact,
    build_optimization_artifact_reference,
    compute_artifact_content_hash,
)
from intergrax.runtime.context_lifecycle.serialization import (
    artifact_compatibility_result_to_safe_dict,
    artifact_creation_coordination_result_to_safe_dict,
    artifact_creation_reservation_to_safe_dict,
    artifact_lookup_key_to_canonical_dict,
    compute_artifact_lookup_key_hash,
    compute_durable_compaction_policy_hash,
    compute_durable_compaction_source_identity_hash,
    context_optimization_policy_to_safe_dict,
    durable_compaction_activation_requirements_to_canonical_dict,
    durable_compaction_policy_from_canonical_dict,
    durable_compaction_policy_to_canonical_dict,
    durable_compaction_source_identity_from_canonical_dict,
    durable_compaction_source_identity_to_canonical_dict,
    durable_compaction_stability_evidence_from_canonical_dict,
    durable_compaction_stability_evidence_to_canonical_dict,
    optimization_artifact_reference_to_safe_dict,
    optimization_artifact_repository_capabilities_to_safe_dict,
    optimization_execution_guard_to_safe_dict,
    reusable_optimization_artifact_to_safe_dict,
    stored_optimization_artifact_to_safe_dict,
)

__all__ = [
    "assess_durable_compaction_eligibility",
    "ArtifactCompatibilityReason",
    "ArtifactCompatibilityResult",
    "ArtifactCompatibilityStatus",
    "ArtifactCompressionTarget",
    "ArtifactCreationCoordinationResult",
    "ArtifactCreationCoordinationStatus",
    "ArtifactCreationReservation",
    "ArtifactLookupKey",
    "ArtifactSourceRange",
    "ArtifactValidationStatus",
    "ArtifactValidationSummary",
    "ContextOptimizationDecision",
    "ContextOptimizationMode",
    "ContextOptimizationPolicy",
    "ContextOptimizationReasonCode",
    "DurableCompactionActivationMode",
    "DurableCompactionActivationRequirements",
    "DurableCompactionEligibilityDecision",
    "DurableCompactionEligibilityReasonCode",
    "DurableCompactionPolicy",
    "DurableCompactionSourceIdentity",
    "DurableCompactionStabilityEvidence",
    "DurableCompactionValidationRequirement",
    "EphemeralArtifactPersistencePolicy",
    "InMemoryOptimizationArtifactRepository",
    "SQLiteOptimizationArtifactRepository",
    "ModelCallExecutionScope",
    "OptimizationArtifactReference",
    "OptimizationArtifactRepository",
    "OptimizationArtifactRepositoryCapabilities",
    "OptimizationArtifactType",
    "OptimizationExecutionGuard",
    "ReusableArtifactStatus",
    "ReusableOptimizationArtifact",
    "StoredOptimizationArtifact",
    "artifact_compatibility_result_to_safe_dict",
    "artifact_creation_coordination_result_to_safe_dict",
    "artifact_creation_reservation_to_safe_dict",
    "artifact_lookup_key_to_canonical_dict",
    "build_optimization_artifact_reference",
    "compute_artifact_content_hash",
    "compute_artifact_lookup_key_hash",
    "compute_durable_compaction_policy_hash",
    "compute_durable_compaction_source_identity_hash",
    "context_optimization_policy_to_safe_dict",
    "durable_compaction_activation_requirements_to_canonical_dict",
    "durable_compaction_policy_from_canonical_dict",
    "durable_compaction_policy_to_canonical_dict",
    "durable_compaction_source_identity_from_canonical_dict",
    "durable_compaction_source_identity_to_canonical_dict",
    "durable_compaction_stability_evidence_from_canonical_dict",
    "durable_compaction_stability_evidence_to_canonical_dict",
    "optimization_artifact_reference_to_safe_dict",
    "optimization_artifact_repository_capabilities_to_safe_dict",
    "optimization_execution_guard_to_safe_dict",
    "reusable_optimization_artifact_to_safe_dict",
    "stored_optimization_artifact_to_safe_dict",
]
