# © Artur Czarnecki. All rights reserved.
# Intergrax framework – proprietary and confidential.

from intergrax.hosting.contracts import (
    HOSTED_APPLICATION_PROFILE_SPEC_VERSION,
    ComponentFailurePolicy,
    HookFailurePolicy,
    HostedApplicationClock,
    HostedApplicationComponent,
    HostedApplicationComponentHealth,
    HostedApplicationComponentRegistration,
    HostedApplicationComponentState,
    HostedApplicationContext,
    HostedApplicationContextPublicView,
    HostedApplicationEvent,
    HostedApplicationEventPublisher,
    HostedApplicationEventSubscription,
    HostedApplicationEventType,
    HostedApplicationHook,
    HostedApplicationHookMode,
    HostedApplicationHookPoint,
    HostedApplicationHooks,
    HostedApplicationIdentity,
    HostedApplicationLifecycleSnapshot,
    HostedApplicationLifecycleSnapshotProvider,
    HostedApplicationLifecycleState,
    HostedApplicationLogger,
    HostedApplicationPaths,
    HostedApplicationProcessIdentity,
    HostedApplicationProfile,
    HostedApplicationProfilePublicView,
    HostedApplicationShutdownCoordinator,
    HostedApplicationShutdownRequestSnapshot,
    InstancePolicy,
    LifecyclePolicy,
    RestartPolicy,
    ShutdownPolicy,
)
from intergrax.hosting.engine.definition import (
    HostedApplicationDefinition,
    HostedApplicationDefinitionPublicView,
    resolve_hosted_application_definition,
)
from intergrax.hosting.engine.diagnostics import (
    HostedApplicationDiagnosticSnapshot,
    HostedApplicationEngineTerminalResult,
    HostedApplicationFailurePhase,
    HostedApplicationFailureRecord,
)
from intergrax.hosting.engine.engine import HostedApplicationEngine
from intergrax.hosting.engine.health import (
    HostedApplicationHealthSnapshot,
    HostedApplicationReadinessService,
)
from intergrax.hosting.instance.contracts import HostedApplicationInstanceAcquisitionResult
from intergrax.hosting.engine.ports import HostedApplicationRuntime
from intergrax.hosting.errors import (
    HostedApplicationComponentError,
    HostedApplicationConfigurationError,
    HostedApplicationControlError,
    HostedApplicationDefinitionError,
    HostedApplicationEngineError,
    HostedApplicationHookError,
    HostedApplicationInstanceConflictError,
    HostedApplicationInstanceGuardError,
    HostedApplicationInstanceOwnershipError,
    HostedApplicationLifecycleTransitionError,
    HostedApplicationRestartPolicyError,
    HostedApplicationRuntimeError,
    HostedApplicationShutdownError,
    HostedApplicationShutdownTimeoutError,
    HostedApplicationSignalError,
    HostedApplicationStartupError,
    HostedApplicationSupervisorError,
)
from intergrax.hosting.eventing import RuntimeSpineHostedApplicationEventPublisher
from intergrax.hosting.services import HostedApplicationServiceRegistry
from intergrax.hosting.control import (
    HostedApplicationControlCoordinator,
    HostedApplicationControlIntent,
    HostedApplicationControlSnapshot,
    HostedApplicationRestartRequestSnapshot,
)
from intergrax.hosting.contracts.lifecycle import HostedApplicationEffectiveControlRequest
from intergrax.hosting.instance import FileHostedApplicationInstanceGuard
from intergrax.hosting.instance.contracts import HostedApplicationInstanceLeasePublicView
from intergrax.hosting.shutdown import (
    HostedApplicationActiveWorkController,
    HostedApplicationFlushService,
    HostedApplicationShutdownExecutionSnapshot,
)
from intergrax.hosting.signals import PortableForegroundSignalAdapter
from intergrax.hosting.runner import run_hosted_application
from intergrax.hosting.supervisor import (
    HostedApplicationEngineFactory,
    HostedApplicationExitKind,
    HostedApplicationExitRecord,
    HostedApplicationRestartDecision,
    HostedApplicationRestartPolicyEvaluator,
    HostedApplicationSupervisor,
    HostedApplicationSupervisorLaunchContext,
    HostedApplicationSupervisorResult,
)

__all__ = [
    "HOSTED_APPLICATION_PROFILE_SPEC_VERSION",
    "ComponentFailurePolicy",
    "HookFailurePolicy",
    "HostedApplicationClock",
    "HostedApplicationComponent",
    "HostedApplicationComponentHealth",
    "HostedApplicationComponentRegistration",
    "HostedApplicationComponentState",
    "HostedApplicationContext",
    "HostedApplicationContextPublicView",
    "HostedApplicationDefinition",
    "HostedApplicationDefinitionPublicView",
    "HostedApplicationDiagnosticSnapshot",
    "HostedApplicationEngine",
    "HostedApplicationEngineTerminalResult",
    "HostedApplicationEngineError",
    "HostedApplicationConfigurationError",
    "HostedApplicationDefinitionError",
    "HostedApplicationLifecycleTransitionError",
    "HostedApplicationStartupError",
    "HostedApplicationShutdownError",
    "HostedApplicationHookError",
    "HostedApplicationComponentError",
    "HostedApplicationRuntimeError",
    "HostedApplicationControlCoordinator",
    "HostedApplicationControlIntent",
    "HostedApplicationControlSnapshot",
    "HostedApplicationEffectiveControlRequest",
    "HostedApplicationRestartRequestSnapshot",
    "HostedApplicationActiveWorkController",
    "HostedApplicationFlushService",
    "HostedApplicationShutdownExecutionSnapshot",
    "HostedApplicationInstanceLeasePublicView",
    "HostedApplicationInstanceAcquisitionResult",
    "FileHostedApplicationInstanceGuard",
    "PortableForegroundSignalAdapter",
    "HostedApplicationExitKind",
    "HostedApplicationExitRecord",
    "HostedApplicationRestartDecision",
    "HostedApplicationRestartPolicyEvaluator",
    "HostedApplicationSupervisor",
    "HostedApplicationSupervisorResult",
    "HostedApplicationSupervisorLaunchContext",
    "HostedApplicationEngineFactory",
    "HostedApplicationControlError",
    "HostedApplicationInstanceConflictError",
    "HostedApplicationInstanceGuardError",
    "HostedApplicationInstanceOwnershipError",
    "HostedApplicationRestartPolicyError",
    "HostedApplicationShutdownTimeoutError",
    "HostedApplicationSignalError",
    "HostedApplicationSupervisorError",
    "HostedApplicationEvent",
    "HostedApplicationEventPublisher",
    "HostedApplicationEventSubscription",
    "HostedApplicationEventType",
    "HostedApplicationFailurePhase",
    "HostedApplicationFailureRecord",
    "HostedApplicationHealthSnapshot",
    "HostedApplicationHook",
    "HostedApplicationHookMode",
    "HostedApplicationHookPoint",
    "HostedApplicationHooks",
    "HostedApplicationIdentity",
    "HostedApplicationLifecycleSnapshot",
    "HostedApplicationLifecycleSnapshotProvider",
    "HostedApplicationLifecycleState",
    "HostedApplicationLogger",
    "HostedApplicationPaths",
    "HostedApplicationProcessIdentity",
    "HostedApplicationProfile",
    "HostedApplicationProfilePublicView",
    "HostedApplicationReadinessService",
    "HostedApplicationRuntime",
    "HostedApplicationServiceRegistry",
    "HostedApplicationShutdownCoordinator",
    "HostedApplicationShutdownRequestSnapshot",
    "InstancePolicy",
    "LifecyclePolicy",
    "RestartPolicy",
    "RuntimeSpineHostedApplicationEventPublisher",
    "ShutdownPolicy",
    "resolve_hosted_application_definition",
    "run_hosted_application",
]
