# © Artur Czarnecki. All rights reserved.

"""Collaborative Work platform domain — membership, delegation, and authority resolution."""

from intergrax.collaborative_work.authority import CollaborativeWorkAuthorityResolver
from intergrax.collaborative_work.policy_composition import compose_policy_decisions
from intergrax.collaborative_work.in_memory_repository import (
    InMemoryAuthorityDelegationRepository,
    InMemoryCollaborativePolicyRepository,
    InMemoryPrincipalAuthorityRepository,
    InMemoryWorkspaceMembershipRepository,
)
from intergrax.collaborative_work.policy_source import CollaborativePolicyEvaluator
from intergrax.collaborative_work.repository import (
    AuthorityDelegationAlreadyExists,
    AuthorityDelegationIdempotencyConflict,
    AuthorityDelegationNotFound,
    AuthorityDelegationRepository,
    AuthorityDelegationRevisionConflict,
    AuthorityDelegationScopeKey,
    CollaborativePolicyRepository,
    CollaborativePolicyRuleAlreadyExists,
    CollaborativePolicyRuleIdempotencyConflict,
    CollaborativePolicyRuleNotFound,
    CollaborativePolicyRuleRevisionConflict,
    CollaborativePolicyRuleScopeKey,
    CollaborativeWorkRepositoryCapabilities,
    CreateAuthorityDelegationCommand,
    CreateCollaborativePolicyRuleCommand,
    CreatePrincipalAuthorityGrantCommand,
    CreateWorkspaceMembershipCommand,
    INITIAL_RECORD_REVISION,
    PrincipalAuthorityGrantAlreadyExists,
    PrincipalAuthorityGrantIdempotencyConflict,
    PrincipalAuthorityGrantNotFound,
    PrincipalAuthorityRepository,
    PrincipalAuthorityGrantRevisionConflict,
    PrincipalAuthorityGrantScopeKey,
    UpdateAuthorityDelegationCommand,
    UpdateCollaborativePolicyRuleCommand,
    UpdatePrincipalAuthorityGrantCommand,
    UpdateWorkspaceMembershipCommand,
    WorkspaceMembershipAlreadyExists,
    WorkspaceMembershipIdempotencyConflict,
    WorkspaceMembershipNotFound,
    WorkspaceMembershipRepository,
    WorkspaceMembershipRevisionConflict,
    WorkspaceMembershipScopeKey,
)

__all__ = [
    "CollaborativeWorkAuthorityResolver",
    "CollaborativePolicyEvaluator",
    "compose_policy_decisions",
    "INITIAL_RECORD_REVISION",
    "AuthorityDelegationAlreadyExists",
    "AuthorityDelegationIdempotencyConflict",
    "AuthorityDelegationNotFound",
    "AuthorityDelegationRepository",
    "AuthorityDelegationRevisionConflict",
    "AuthorityDelegationScopeKey",
    "CollaborativePolicyRepository",
    "CollaborativePolicyRuleAlreadyExists",
    "CollaborativePolicyRuleIdempotencyConflict",
    "CollaborativePolicyRuleNotFound",
    "CollaborativePolicyRuleRevisionConflict",
    "CollaborativePolicyRuleScopeKey",
    "CollaborativeWorkRepositoryCapabilities",
    "CreateAuthorityDelegationCommand",
    "CreateCollaborativePolicyRuleCommand",
    "CreatePrincipalAuthorityGrantCommand",
    "CreateWorkspaceMembershipCommand",
    "InMemoryAuthorityDelegationRepository",
    "InMemoryCollaborativePolicyRepository",
    "InMemoryPrincipalAuthorityRepository",
    "InMemoryWorkspaceMembershipRepository",
    "PrincipalAuthorityGrantAlreadyExists",
    "PrincipalAuthorityGrantIdempotencyConflict",
    "PrincipalAuthorityGrantNotFound",
    "PrincipalAuthorityRepository",
    "PrincipalAuthorityGrantRevisionConflict",
    "PrincipalAuthorityGrantScopeKey",
    "UpdateAuthorityDelegationCommand",
    "UpdateCollaborativePolicyRuleCommand",
    "UpdatePrincipalAuthorityGrantCommand",
    "UpdateWorkspaceMembershipCommand",
    "WorkspaceMembershipAlreadyExists",
    "WorkspaceMembershipIdempotencyConflict",
    "WorkspaceMembershipNotFound",
    "WorkspaceMembershipRepository",
    "WorkspaceMembershipRevisionConflict",
    "WorkspaceMembershipScopeKey",
]
