# © Artur Czarnecki. All rights reserved.

"""CTRL-X wide pyright scan file list."""

from __future__ import annotations

from typing import Final

CTRL_X_WIDE_PYRIGHT_BASELINE_HEAD: Final[str] = "3e574ea35ee2e3f9e9adac4088cd51ae89ed469c"
CTRL_X_WIDE_PYRIGHT_R1_START_HEAD: Final[str] = "5e9878d71d363542d25ada19cff2590aa37448d3"

CTRL_X_WIDE_PYRIGHT_FILE_PATHS: Final[tuple[str, ...]] = ('intergrax/applications/_shared/application_security_wiring.py', 'intergrax/context/bootstrap.py', 'intergrax/context/budget/compaction_apply.py', 'intergrax/context/budget/compaction_validation.py', 'intergrax/context/orchestrator.py', 'intergrax/context/planning.py', 'intergrax/context/policy/conflict_resolver.py', 'intergrax/context/policy/exact_dedup.py', 'intergrax/context/policy/invariants.py', 'intergrax/context/providers/builtin.py', 'intergrax/context/providers/legacy_bridge.py', 'intergrax/context/providers/session_semantic_recall.py', 'intergrax/context/ranker.py', 'intergrax/context/session_history.py', 'intergrax/context/tracking/context_spans.py', 'intergrax/runtime/diagnostics/__init__.py', 'intergrax/runtime/diagnostics/central_terminal_execution_diagnostic_port.py', 'intergrax/runtime/nexus/tools/agent_governance_approval_pause_bridge.py', 'intergrax/runtime/nexus/tools/atomic_planner_round.py', 'intergrax/runtime/nexus/tools/catalog_context.py', 'intergrax/runtime/nexus/tools/catalog_dispatch.py', 'intergrax/runtime/nexus/tools/catalog_tool_planner.py', 'intergrax/runtime/nexus/tools/continuation_aware_catalog_tool_host.py', 'intergrax/runtime/nexus/tools/declarative_policy_hitl_bridge.py', 'intergrax/runtime/nexus/tools/hierarchical_tool_selector.py', 'intergrax/runtime/nexus/tools/invoker.py', 'intergrax/runtime/nexus/tools/mse_governed_continuation_hitl_bridge.py', 'intergrax/runtime/nexus/tools/patterns/deterministic_chain.py', 'intergrax/runtime/nexus/tools/patterns/parallel_semantic_batch.py', 'intergrax/runtime/nexus/tools/patterns/single_pass.py', 'intergrax/runtime/nexus/tools/plan_context_invocation.py', 'intergrax/runtime/nexus/tools/public_tool_invocation_pattern_bridge.py', 'intergrax/runtime/nexus/tools/tool_loop.py', 'intergrax/runtime/observability/__init__.py', 'intergrax/runtime/observability/exporters/__init__.py', 'intergrax/runtime/observability/exporters/otlp/__init__.py', 'intergrax/runtime/registry/agent_registry_read.py', 'intergrax/runtime/security/defense_plugin.py', 'intergrax/runtime/security/encryption_middleware.py', 'intergrax/skills/catalog.py', 'intergrax/skills/core/contracts.py', 'intergrax/skills/core/manifest.py', 'intergrax/skills/core/plugin.py', 'intergrax/skills/dynamic_acquisition.py', 'intergrax/skills/integration/contract_resolution.py', 'intergrax/skills/providers/catalog/plugin.py', 'intergrax/skills/providers/cloud_platform/plugin.py', 'intergrax/skills/providers/code/plugin.py', 'intergrax/skills/providers/gitlab/plugin.py', 'intergrax/skills/providers/http/plugin.py', 'intergrax/skills/providers/jira/plugin.py', 'intergrax/skills/providers/ml/plugin.py', 'intergrax/skills/providers/openai/plugin.py')
