# © Artur Czarnecki. All rights reserved.
# Intergrax framework – proprietary and confidential.
# Use, modification, or distribution without written permission is prohibited.

"""Harness runtime evidence contracts (HEP Band 2ae)."""

from intergrax.runtime.evidence.core_certification_spec import (
    CORE_CERTIFICATION_EVIDENCE_KIND,
    CORE_LEVEL_SCENARIOS,
    CORE_SCENARIO_CATALOG_ORDER,
    CoreCertificationLevel,
    CoreCertificationMode,
    CoreCertificationSurface,
    is_scenario_in_level,
    normalize_core_level,
    scenario_ids_for_level,
)
from intergrax.runtime.evidence.scenario_contracts import (
    CORE_SCENARIO_CONTRACTS,
    CoreEvidenceRef,
    CoreScenarioContract,
    CoreScenarioExpectation,
    CoreScenarioResult,
    CoreScenarioStatus,
    EvidenceRefKind,
    core_scenario_contracts_for_level,
    get_core_scenario_contract,
    validate_core_scenario_catalog,
)

from intergrax.runtime.evidence.certification_report import (
    CoreCertificationReport,
    DEFAULT_CORE_CERTIFICATION_OUTPUT_DIR,
    build_core_certification_report,
    write_core_certification_report,
)
from intergrax.runtime.evidence.scenario_runner import run_core_certification, run_core_scenario
from intergrax.runtime.evidence.trace_timeline_contracts import (
    TraceTimeline,
    TraceTimelineArtifactKind,
    TraceTimelineArtifactRef,
    TraceTimelineEvent,
    TraceTimelineEventKind,
    TraceTimelineKind,
    TraceTimelineSeverity,
    TraceTimelineSourceKind,
    TraceTimelineSourceRef,
    create_trace_timeline_event,
    generate_timeline_event_id,
    validate_trace_timeline,
)
from intergrax.runtime.evidence.trace_timeline_adapter import (
    build_timeline_from_certification_report,
    load_core_certification_report,
)
from intergrax.runtime.evidence.trace_timeline_export import (
    DEFAULT_TRACE_EVIDENCE_OUTPUT_DIR,
    TRACE_TIMELINE_OPERATOR_NOTE,
    format_trace_timeline_cli,
    format_trace_timeline_markdown,
    write_trace_timeline,
)
from intergrax.runtime.evidence.trace_timeline_facets import (
    TraceBudgetFacet,
    TraceBudgetStatus,
    TraceEvidenceFacet,
    TraceEvidenceOrigin,
    TraceHitlFacet,
    TraceHitlStatus,
    TracePolicyFacet,
    TracePolicyOutcome,
    TraceScenarioLifecycleFacet,
    TraceScenarioPhase,
    TraceTimelineEventFacets,
    validate_trace_timeline_event_facets,
)

__all__ = [
    "CORE_CERTIFICATION_EVIDENCE_KIND",
    "CORE_LEVEL_SCENARIOS",
    "CORE_SCENARIO_CATALOG_ORDER",
    "CORE_SCENARIO_CONTRACTS",
    "CoreCertificationLevel",
    "CoreCertificationMode",
    "CoreCertificationSurface",
    "CoreCertificationReport",
    "CoreEvidenceRef",
    "CoreScenarioContract",
    "CoreScenarioExpectation",
    "CoreScenarioResult",
    "CoreScenarioStatus",
    "DEFAULT_CORE_CERTIFICATION_OUTPUT_DIR",
    "DEFAULT_TRACE_EVIDENCE_OUTPUT_DIR",
    "EvidenceRefKind",
    "build_core_certification_report",
    "build_timeline_from_certification_report",
    "format_trace_timeline_cli",
    "format_trace_timeline_markdown",
    "load_core_certification_report",
    "core_scenario_contracts_for_level",
    "get_core_scenario_contract",
    "is_scenario_in_level",
    "normalize_core_level",
    "run_core_certification",
    "run_core_scenario",
    "scenario_ids_for_level",
    "TraceTimeline",
    "TraceTimelineArtifactKind",
    "TraceTimelineArtifactRef",
    "TraceTimelineEvent",
    "TraceTimelineEventKind",
    "TraceTimelineKind",
    "TraceTimelineSeverity",
    "TraceTimelineSourceKind",
    "TraceTimelineSourceRef",
    "TRACE_TIMELINE_OPERATOR_NOTE",
    "TraceBudgetFacet",
    "TraceBudgetStatus",
    "TraceEvidenceFacet",
    "TraceEvidenceOrigin",
    "TraceHitlFacet",
    "TraceHitlStatus",
    "TracePolicyFacet",
    "TracePolicyOutcome",
    "TraceScenarioLifecycleFacet",
    "TraceScenarioPhase",
    "TraceTimelineEventFacets",
    "create_trace_timeline_event",
    "generate_timeline_event_id",
    "validate_core_scenario_catalog",
    "validate_trace_timeline",
    "validate_trace_timeline_event_facets",
    "write_core_certification_report",
    "write_trace_timeline",
]
