# © Artur Czarnecki. All rights reserved.
# Intergrax framework – proprietary and confidential.

"""Provider filesystem layout — slug → primary category folder (Phase M.6)."""

from __future__ import annotations

# Primary IntegrationCategory folder for each catalog slug.
SLUG_CATEGORY: dict[str, str] = {
    "sqlite": "relational_store",
    "postgresql": "relational_store",
    "mysql": "relational_store",
    "databricks": "relational_store",
    "oracle": "relational_store",
    "mssql": "relational_store",
    "azure_sql": "relational_store",
    "cloud_sql": "relational_store",
    "cassandra": "document_store",
    "mongodb": "document_store",
    "dynamodb": "document_store",
    "redis": "key_value_cache",
    "memcached": "key_value_cache",
    "elasticache": "key_value_cache",
    "kafka": "message_bus",
    "celery": "message_bus",
    "rabbitmq": "message_bus",
    "sqs": "message_bus",
    "service_bus": "message_bus",
    "pubsub": "message_bus",
    "s3": "object_storage",
    "azure_blob": "object_storage",
    "gcs": "object_storage",
    "pinecone": "vector_store",
    "qdrant": "vector_store",
    "chroma": "vector_store",
    "google_cse": "search_provider",
    "bing": "search_provider",
    "brave": "search_provider",
    "serpapi": "search_provider",
    "slack": "notification_channel",
    "teams": "notification_channel",
    "webhook": "notification_channel",
    "log": "notification_channel",
    "email_smtp": "notification_channel",
    "lab_json": "interaction_surface",
    "slash_command": "interaction_surface",
    "ms365_graph": "collaboration_suite",
    "google_workspace": "collaboration_suite",
    "jira": "issue_tracker",
    "github": "issue_tracker",
    "linear": "issue_tracker",
    "azure_devops": "issue_tracker",
    "confluence": "wiki_knowledge",
    "notion": "wiki_knowledge",
    "sharepoint": "wiki_knowledge",
    "prometheus": "observability_backend",
    "elasticsearch": "observability_backend",
    "otel": "observability_backend",
    "playwright": "browser_automation",
    "aws": "cloud_platform",
    "azure": "cloud_platform",
    "gcp": "cloud_platform",
    "tavily": "search_provider",
    "exa": "search_provider",
    "weaviate": "vector_store",
    "milvus": "vector_store",
    "inmemory": "vector_store",
    "vault": "secrets_store",
    "langfuse": "observability_backend",
    "datadog": "observability_backend",
    "clickhouse": "observability_backend",
    "sentry": "observability_backend",
    "temporal": "message_bus",
    "nats": "message_bus",
    "neo4j": "graph_store",
    "snowflake": "relational_store",
    "supabase": "relational_store",
    "minio": "object_storage",
    "filesystem": "object_storage",
    "discord": "notification_channel",
    "twilio": "notification_channel",
    "firecrawl": "browser_automation",
    "selenium": "browser_automation",
    "docling": "document_parser",
    "pymupdf": "document_parser",
    "unstructured": "document_parser",
    "python_docx": "document_parser",
    "openpyxl": "document_parser",
    "whisper": "document_parser",
    "yt_dlp": "document_parser",
    "cohere_rerank": "rerank_provider",
    "jina_rerank": "rerank_provider",
    "langsmith": "observability_backend",
    "helicone": "observability_backend",
    "posthog": "observability_backend",
    "braintrust": "observability_backend",
    "signoz": "observability_backend",
    "honeycomb": "observability_backend",
    "arize": "observability_backend",
    "phoenix": "observability_backend",
    "wandb": "observability_backend",
    "opensearch": "observability_backend",
    "pagerduty": "notification_channel",
    "opsgenie": "notification_channel",
    "gitlab": "issue_tracker",
    "vespa": "vector_store",
    "reddit": "search_provider",
    "google_places": "search_provider",
    "pgvector": "vector_store",
    "duckdb": "relational_store",
    "influxdb": "observability_backend",
    "timescaledb": "relational_store",
    "grafana": "observability_backend",
    "loki": "observability_backend",
    "tempo": "observability_backend",
    "aws_secrets_manager": "secrets_store",
    "azure_key_vault": "secrets_store",
    "gcp_secret_manager": "secrets_store",
    "doppler": "secrets_store",
    "unleash": "feature_flag",
    "launchdarkly": "feature_flag",
    "github_actions": "ci_cd",
    "redpanda": "message_bus",
    "cloudflare_r2": "object_storage",
    "memgraph": "graph_store",
    "falkordb": "graph_store",
    "incident_io": "notification_channel",
    "kubernetes": "cloud_platform",
    "servicenow": "issue_tracker",
    "bitbucket": "issue_tracker",
    "asana": "issue_tracker",
    "sendgrid": "notification_channel",
    "mailgun": "interaction_surface",
    "mlflow": "observability_backend",
    "huggingface_hub": "object_storage",
    "ollama": "interaction_surface",
    "gitlab_ci": "ci_cd",
    "circleci": "ci_cd",
    "azure_pipelines": "ci_cd",
    "mailpit": "notification_channel",
    "localstack": "cloud_platform",
    "codecov": "ci_cd",
    "grafana_oncall": "notification_channel",
    "opentelemetry_collector": "observability_backend",
}


def provider_import_path(slug: str) -> str:
    """Dotted import path for a provider package, e.g. ``...providers.object_storage.s3``."""
    category = SLUG_CATEGORY[slug]
    return f"intergrax.integrations.providers.{category}.{slug}"


def provider_package_path(slug: str) -> str:
    """Repo-relative path to provider directory."""
    category = SLUG_CATEGORY[slug]
    return f"intergrax/integrations/providers/{category}/{slug}"


__all__ = ["SLUG_CATEGORY", "provider_import_path", "provider_package_path"]
