# © Artur Czarnecki. All rights reserved.
# Intergrax framework – proprietary and confidential.

"""Enterprise Reliability Layer contracts (ERL — UNKNOWN, effect contracts, reconciliation, plugin SPI)."""

from intergrax.contracts.enterprise_reliability.effect_contract import (
    ExternalEffectCapabilitySupport,
    ExternalEffectCategory,
    ExternalEffectContract,
    ExternalEffectContractValidationError,
    ExternalEffectSafetyCapabilities,
    UnknownUncertaintyPosture,
    contract_declares_compensation,
    contract_declares_idempotency,
    contract_declares_reconciliation,
    evaluate_unknown_uncertainty_posture,
    validate_external_effect_contract,
)
from intergrax.contracts.enterprise_reliability.evidence import (
    ExternalEffectEvidenceVerdict,
    classify_external_effect_outcome,
    external_effect_outcome_from_physical_state,
)
from intergrax.contracts.enterprise_reliability.gating import (
    DependentExecutionGateAction,
    DependentExecutionGateRequest,
    DependentExecutionGateResult,
    evaluate_dependent_execution_gate,
)
from intergrax.contracts.enterprise_reliability.lifecycle import (
    UncertaintyLifecyclePhase,
    UncertaintyLifecycleTransitionError,
    UncertaintyResolutionKind,
    UncertaintyStateRecord,
    assert_uncertainty_lifecycle_transition,
    initial_uncertainty_state,
)
from intergrax.contracts.enterprise_reliability.observability import (
    ReconciliationAttemptFact,
    ReconciliationPlanFact,
    UncertaintyAdmissionFact,
    UncertaintyGatingFact,
)
from intergrax.contracts.enterprise_reliability.outcome import (
    ExternalEffectOutcome,
    is_terminal_external_effect_outcome,
)
from intergrax.contracts.enterprise_reliability.plugin_spi import (
    CompensationStrategy,
    CompensationStrategyAdvice,
    EnterpriseReliabilityCapabilityKind,
    EnterpriseReliabilityPlugin,
    EnterpriseReliabilityPluginDescriptor,
    EnterpriseReliabilityPluginGateway,
    EnterpriseReliabilityPluginRegistry,
    EnterpriseReliabilityRiskLevel,
    EnterpriseReliabilityStrategyContext,
    ReconciliationProbeExecutor,
    ReconciliationStrategy,
    ReconciliationStrategyAdvice,
    ResolutionStrategy,
    ResolutionStrategyAdvice,
    RiskEvaluationStrategy,
    RiskEvaluationStrategyAdvice,
    assert_plugin_identity_matches_descriptor,
)
from intergrax.contracts.enterprise_reliability.reconciliation import (
    ReconciliationBounds,
    ReconciliationDisposition,
    ReconciliationPlan,
    ReconciliationPlanningError,
    assert_reconciliation_probe_ref,
    build_reconciliation_plan,
    default_contract_probe_ref,
    default_reconciliation_bounds,
    evaluate_reconciliation_disposition,
)
from intergrax.contracts.enterprise_reliability.reconciliation_execution import (
    ExternalEffectReconciliationExecution,
    ReconciliationExecutionDisposition,
    ReconciliationExecutionError,
    ReconciliationProbeRequest,
    ReconciliationProbeResult,
    build_reconciliation_probe_request,
)
from intergrax.contracts.enterprise_reliability.reliability_boundary import (
    ExternalEffectReliabilityInteraction,
    ExternalEffectReliabilityProjection,
    project_external_effect_to_reliability,
)

__all__ = [
    "DependentExecutionGateAction",
    "DependentExecutionGateRequest",
    "DependentExecutionGateResult",
    "ExternalEffectCapabilitySupport",
    "ExternalEffectCategory",
    "ExternalEffectContract",
    "ExternalEffectContractValidationError",
    "ExternalEffectEvidenceVerdict",
    "ExternalEffectOutcome",
    "ExternalEffectSafetyCapabilities",
    "CompensationStrategy",
    "CompensationStrategyAdvice",
    "EnterpriseReliabilityCapabilityKind",
    "EnterpriseReliabilityPlugin",
    "EnterpriseReliabilityPluginDescriptor",
    "EnterpriseReliabilityPluginGateway",
    "EnterpriseReliabilityPluginRegistry",
    "EnterpriseReliabilityRiskLevel",
    "EnterpriseReliabilityStrategyContext",
    "ExternalEffectReliabilityInteraction",
    "ExternalEffectReliabilityProjection",
    "ExternalEffectReconciliationExecution",
    "ReconciliationAttemptFact",
    "ReconciliationExecutionDisposition",
    "ReconciliationExecutionError",
    "ReconciliationProbeExecutor",
    "ReconciliationProbeRequest",
    "ReconciliationProbeResult",
    "ReconciliationStrategy",
    "ReconciliationBounds",
    "ReconciliationDisposition",
    "ReconciliationPlan",
    "ReconciliationPlanningError",
    "ReconciliationPlanFact",
    "ResolutionStrategy",
    "ResolutionStrategyAdvice",
    "RiskEvaluationStrategy",
    "RiskEvaluationStrategyAdvice",
    "UncertaintyAdmissionFact",
    "UncertaintyGatingFact",
    "UncertaintyLifecyclePhase",
    "UncertaintyLifecycleTransitionError",
    "UncertaintyResolutionKind",
    "UncertaintyStateRecord",
    "UnknownUncertaintyPosture",
    "assert_plugin_identity_matches_descriptor",
    "assert_uncertainty_lifecycle_transition",
    "classify_external_effect_outcome",
    "contract_declares_compensation",
    "contract_declares_idempotency",
    "contract_declares_reconciliation",
    "evaluate_dependent_execution_gate",
    "ReconciliationStrategyAdvice",
    "evaluate_unknown_uncertainty_posture",
    "build_reconciliation_plan",
    "build_reconciliation_probe_request",
    "default_contract_probe_ref",
    "default_reconciliation_bounds",
    "evaluate_reconciliation_disposition",
    "external_effect_outcome_from_physical_state",
    "initial_uncertainty_state",
    "is_terminal_external_effect_outcome",
    "project_external_effect_to_reliability",
    "validate_external_effect_contract",
]
