# © Artur Czarnecki. All rights reserved.

"""Explicit TRACE-X-P4-R5 sanctioned production composition site registry."""

from __future__ import annotations

from typing import Final

from tests.qualification.trace_x._trace_x_p4_production_composition_types import (
    ProductionCompositionSiteClassification,
    ProductionCompositionSiteKind,
    RegisteredProductionCompositionSite,
)

PRODUCTION_COMPOSITION_SITE_REGISTRY: Final[tuple[RegisteredProductionCompositionSite, ...]] = (
    RegisteredProductionCompositionSite(
        path="agents/external_contractor_adapter/external_contractor_adapter_agent.py",
        site_kind=ProductionCompositionSiteKind.RUNTIME_CONFIG_LLM_ADAPTER_KW,
        line_number=84,
        classification=ProductionCompositionSiteClassification.DEVELOPMENT_LAB_OR_NON_STRICT_RUNTIME,
        composition_anchor="Tier-2 agent local RuntimeConfig",
        inference_executor_supplied=False,
        p4_wrap_applied=False,
        evidence_nodeid="test_trace_x_p4_r5_closed_world.py::test_txp4r5_q04_production_composition_registry_parity",
    ),
    RegisteredProductionCompositionSite(
        path="agents/organization_worker/organization_worker_agent.py",
        site_kind=ProductionCompositionSiteKind.RUNTIME_CONFIG_LLM_ADAPTER_KW,
        line_number=111,
        classification=ProductionCompositionSiteClassification.DEVELOPMENT_LAB_OR_NON_STRICT_RUNTIME,
        composition_anchor="Tier-2 agent local RuntimeConfig",
        inference_executor_supplied=False,
        p4_wrap_applied=False,
        evidence_nodeid="test_trace_x_p4_r5_closed_world.py::test_txp4r5_q04_production_composition_registry_parity",
    ),
    RegisteredProductionCompositionSite(
        path="intergrax/agents/authoring/acp_stub_reflex.py",
        site_kind=ProductionCompositionSiteKind.RUNTIME_CONFIG_LLM_ADAPTER_KW,
        line_number=61,
        classification=ProductionCompositionSiteClassification.DEVELOPMENT_LAB_OR_NON_STRICT_RUNTIME,
        composition_anchor="Authoring stub reflex RuntimeConfig",
        inference_executor_supplied=False,
        p4_wrap_applied=False,
        evidence_nodeid="test_trace_x_p4_r5_closed_world.py::test_txp4r5_q04_production_composition_registry_parity",
    ),
    RegisteredProductionCompositionSite(
        path="intergrax/applications/_shared/acp_runtime_session_hooks.py",
        site_kind=ProductionCompositionSiteKind.RUNTIME_CONFIG_LLM_ADAPTER_KW,
        line_number=48,
        classification=ProductionCompositionSiteClassification.DEVELOPMENT_LAB_OR_NON_STRICT_RUNTIME,
        composition_anchor="ACP session hook RuntimeConfig (not materialize_runtime_config bridge)",
        inference_executor_supplied=False,
        p4_wrap_applied=False,
        evidence_nodeid="test_trace_x_p4_r5_closed_world.py::test_txp4r5_q04_production_composition_registry_parity",
    ),
    RegisteredProductionCompositionSite(
        path="intergrax/applications/_shared/runtime_config_bridge.py",
        site_kind=ProductionCompositionSiteKind.RUNTIME_CONFIG_LLM_ADAPTER_KW,
        line_number=134,
        classification=ProductionCompositionSiteClassification.SANCTIONED_PRODUCTION_ROOT,
        composition_anchor="materialize_runtime_config initial RuntimeConfig",
        inference_executor_supplied=False,
        p4_wrap_applied=None,
        evidence_nodeid="test_trace_x_p4_r5_closed_world.py::test_txp4r5_q10_sanctioned_runtime_config_llm_adapter_wrap_propagation",
    ),
    RegisteredProductionCompositionSite(
        path="intergrax/applications/_shared/runtime_config_bridge.py",
        site_kind=ProductionCompositionSiteKind.SANCTIONED_LLM_ADAPTER_P4_WRAP,
        line_number=162,
        classification=ProductionCompositionSiteClassification.SANCTIONED_PRODUCTION_ROOT,
        composition_anchor="materialize_runtime_config canonical P4 wrap assignment",
        inference_executor_supplied=False,
        p4_wrap_applied=True,
        evidence_nodeid="test_trace_x_p4_r5_closed_world.py::test_txp4r5_q10_sanctioned_runtime_config_llm_adapter_wrap_propagation",
    ),
    RegisteredProductionCompositionSite(
        path="intergrax/runtime/execution/host_task.py",
        site_kind=ProductionCompositionSiteKind.STRATEGY_EXECUTION_ROUTER_INSTANTIATION,
        line_number=255,
        classification=ProductionCompositionSiteClassification.SANCTIONED_PRODUCTION_ROUTER,
        composition_anchor="build_host_task_strategy_router",
        inference_executor_supplied=False,
        p4_wrap_applied=None,
        evidence_nodeid="test_trace_x_p4_r5_closed_world.py::test_txp4r5_q06_inference_executor_unreachable_from_sanctioned_routers",
    ),
    RegisteredProductionCompositionSite(
        path="intergrax/runtime/execution/inference_composition.py",
        site_kind=ProductionCompositionSiteKind.GOVERNED_INFERENCE_EXECUTOR_FACTORY_DEF,
        line_number=31,
        classification=ProductionCompositionSiteClassification.INTERNAL_FACTORY_NO_PRODUCTION_CALLER,
        composition_anchor="build_governed_inference_executor factory definition",
        inference_executor_supplied=False,
        p4_wrap_applied=None,
        evidence_nodeid="test_trace_x_p4_r5_closed_world.py::test_txp4r5_q07_build_governed_inference_executor_no_production_caller",
    ),
    RegisteredProductionCompositionSite(
        path="intergrax/runtime/execution/inference_composition.py",
        site_kind=ProductionCompositionSiteKind.RUNTIME_INFERENCE_EXECUTOR_INSTANTIATION,
        line_number=42,
        classification=ProductionCompositionSiteClassification.INTERNAL_FACTORY_NO_PRODUCTION_CALLER,
        composition_anchor="build_governed_inference_executor constructs InferenceExecutor",
        inference_executor_supplied=False,
        p4_wrap_applied=None,
        evidence_nodeid="test_trace_x_p4_r5_closed_world.py::test_txp4r5_q07_build_governed_inference_executor_no_production_caller",
    ),
    RegisteredProductionCompositionSite(
        path="intergrax/runtime/execution/lab_reference_agent_runtime.py",
        site_kind=ProductionCompositionSiteKind.RUNTIME_CONFIG_LLM_ADAPTER_KW,
        line_number=85,
        classification=ProductionCompositionSiteClassification.DEVELOPMENT_LAB_OR_NON_STRICT_RUNTIME,
        composition_anchor="lab reference agent runtime",
        inference_executor_supplied=False,
        p4_wrap_applied=False,
        evidence_nodeid="test_trace_x_p4_r5_closed_world.py::test_txp4r5_q04_production_composition_registry_parity",
    ),
    RegisteredProductionCompositionSite(
        path="intergrax/runtime/execution/orchestration.py",
        site_kind=ProductionCompositionSiteKind.STRATEGY_EXECUTION_ROUTER_INSTANTIATION,
        line_number=274,
        classification=ProductionCompositionSiteClassification.SANCTIONED_PRODUCTION_ROUTER,
        composition_anchor="root orchestration StrategyExecutionRouter",
        inference_executor_supplied=False,
        p4_wrap_applied=None,
        evidence_nodeid="test_trace_x_p4_r5_closed_world.py::test_txp4r5_q06_inference_executor_unreachable_from_sanctioned_routers",
    ),
    RegisteredProductionCompositionSite(
        path="intergrax/runtime/nexus/agents/catalog_declarative_invoker.py",
        site_kind=ProductionCompositionSiteKind.RUNTIME_CONFIG_LLM_ADAPTER_KW,
        line_number=113,
        classification=ProductionCompositionSiteClassification.DEVELOPMENT_LAB_OR_NON_STRICT_RUNTIME,
        composition_anchor="catalog dispatch LLM stub RuntimeConfig",
        inference_executor_supplied=False,
        p4_wrap_applied=False,
        evidence_nodeid="test_trace_x_p4_r5_closed_world.py::test_txp4r5_q04_production_composition_registry_parity",
    ),
    RegisteredProductionCompositionSite(
        path="intergrax/runtime/nexus/context/context_manager.py",
        site_kind=ProductionCompositionSiteKind.RUNTIME_CONFIG_LLM_ADAPTER_KW,
        line_number=239,
        classification=ProductionCompositionSiteClassification.DEVELOPMENT_LAB_OR_NON_STRICT_RUNTIME,
        composition_anchor="context manager non-strict RuntimeConfig assembly",
        inference_executor_supplied=False,
        p4_wrap_applied=False,
        evidence_nodeid="test_trace_x_p4_r5_closed_world.py::test_txp4r5_q04_production_composition_registry_parity",
    ),
    RegisteredProductionCompositionSite(
        path="intergrax/runtime/nexus/context/uaep_assemble.py",
        site_kind=ProductionCompositionSiteKind.RUNTIME_CONFIG_LLM_ADAPTER_KW,
        line_number=66,
        classification=ProductionCompositionSiteClassification.DEVELOPMENT_LAB_OR_NON_STRICT_RUNTIME,
        composition_anchor="UAEP assemble RuntimeConfig production_mode=False",
        inference_executor_supplied=False,
        p4_wrap_applied=False,
        evidence_nodeid="test_trace_x_p4_r5_closed_world.py::test_txp4r5_q04_production_composition_registry_parity",
    ),
    RegisteredProductionCompositionSite(
        path="intergrax/runtime/nexus/execution/graph_executor.py",
        site_kind=ProductionCompositionSiteKind.STRATEGY_EXECUTION_ROUTER_INSTANTIATION,
        line_number=274,
        classification=ProductionCompositionSiteClassification.SANCTIONED_PRODUCTION_ROUTER,
        composition_anchor="GraphExecutor StrategyExecutionRouter",
        inference_executor_supplied=False,
        p4_wrap_applied=None,
        evidence_nodeid="test_trace_x_p4_r5_closed_world.py::test_txp4r5_q06_inference_executor_unreachable_from_sanctioned_routers",
    ),
    RegisteredProductionCompositionSite(
        path="intergrax/runtime/nexus/tools/nexus_execution_bound_catalog_tool_invoker.py",
        site_kind=ProductionCompositionSiteKind.RUNTIME_CONFIG_LLM_ADAPTER_KW,
        line_number=153,
        classification=ProductionCompositionSiteClassification.DEVELOPMENT_LAB_OR_NON_STRICT_RUNTIME,
        composition_anchor="catalog tool invoker LLM stub RuntimeConfig",
        inference_executor_supplied=False,
        p4_wrap_applied=False,
        evidence_nodeid="test_trace_x_p4_r5_closed_world.py::test_txp4r5_q04_production_composition_registry_parity",
    ),
)

__all__ = ["PRODUCTION_COMPOSITION_SITE_REGISTRY"]
