# © Artur Czarnecki. All rights reserved.

"""Explicit TRACE-X-P4-R4 model-call surface registry."""

from __future__ import annotations

from typing import Final

from tests.qualification.trace_x._trace_x_p4_registry_types import (
    ModelCallSurfaceClassification,
    RegisteredModelCallSurface,
)

MODEL_CALL_SURFACE_REGISTRY: Final[tuple[RegisteredModelCallSurface, ...]] = (
    RegisteredModelCallSurface(
        path='agents/model_routing_qualifier/steps/model_routing_job.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Tier-2 agent step; not enterprise sanctioned primary composition root',
        canonical_owner='Tier-2 agent job',
        canonical_contract='agent-injected LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='agents/tool_selection_qualifier/steps/tool_selection_job.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Tier-2 agent step; not enterprise sanctioned primary composition root',
        canonical_owner='Tier-2 agent job',
        canonical_contract='agent-injected LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='agents/tool_selection_qualifier/steps/tool_selection_job.py',
        method='generate_with_tools',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Tier-2 agent step; not enterprise sanctioned primary composition root',
        canonical_owner='Tier-2 agent job',
        canonical_contract='agent-injected LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='agents/web_search_qualifier/source_selection/llm_selector.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Tier-2 agent step; not enterprise sanctioned primary composition root',
        canonical_owner='Tier-2 agent job',
        canonical_contract='agent-injected LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='agents/web_search_qualifier/steps/web_search_job.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Tier-2 agent step; not enterprise sanctioned primary composition root',
        canonical_owner='Tier-2 agent job',
        canonical_contract='agent-injected LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='applications/local_workspace_application/workspaces/ask_answer_assembler.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Tier-3 application workspace; not sanctioned Nexus primary composition root',
        canonical_owner='Tier-3 application',
        canonical_contract='application-composed LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='applications/local_workspace_application/workspaces/hybrid_ask_answer_assembler.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Tier-3 application workspace; not sanctioned Nexus primary composition root',
        canonical_owner='Tier-3 application',
        canonical_contract='application-composed LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/agents/authoring/llm_router.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Auxiliary intergrax service invoking injected adapter outside ModelCallRuntimeEvidenceAdapter PRIMARY seam',
        canonical_owner='Intergrax auxiliary module',
        canonical_contract='module-local LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/codecraft/llm_codegen_adapter.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Auxiliary intergrax service invoking injected adapter outside ModelCallRuntimeEvidenceAdapter PRIMARY seam',
        canonical_owner='Intergrax auxiliary module',
        canonical_contract='module-local LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/_shared/conformance.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/_shared/conformance.py',
        method='generate_with_tools',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/_shared/conformance.py',
        method='stream_messages',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/_shared/conformance.py',
        method='stream_with_tools',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/providers/aws_bedrock_adapter.py',
        method='generate_with_tools',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/providers/claude_adapter.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/providers/claude_adapter.py',
        method='generate_with_tools',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/providers/cohere_native_adapter.py',
        method='generate_with_tools',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/providers/gemini_adapter.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/providers/gemini_adapter.py',
        method='generate_with_tools',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/providers/mistral_adapter.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/providers/openai_compat_providers.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/providers/openai_compat_providers.py',
        method='generate_structured',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/providers/openai_compat_providers.py',
        method='generate_with_tools',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/providers/openai_compat_providers.py',
        method='stream_messages',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/providers/openai_compat_providers.py',
        method='stream_with_tools',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/registry/catalog_capabilities.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/registry/catalog_capabilities.py',
        method='generate_structured',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/registry/catalog_capabilities.py',
        method='generate_with_tools',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/registry/catalog_capabilities.py',
        method='stream_messages',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/registry/failover_adapter.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/registry/failover_adapter.py',
        method='generate_structured',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/registry/failover_adapter.py',
        method='generate_with_tools',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/registry/failover_adapter.py',
        method='stream_messages',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/registry/failover_adapter.py',
        method='stream_with_tools',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/routing/evaluating_adapter.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/routing/evaluating_adapter.py',
        method='generate_structured',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/routing/evaluating_adapter.py',
        method='generate_with_tools',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/llm_adapters/routing/evaluating_adapter.py',
        method='stream_messages',
        classification=ModelCallSurfaceClassification.NOT_LLM_ADAPTER_CALL,
        semantic_reason='Callee is adapter protocol method body (provider/wrapper); path under intergrax/llm_adapters',
        canonical_owner='LLM adapter implementations',
        canonical_contract='LLMAdapter protocol method implementation',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/memory/strategies/defaults/llm_extraction.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Auxiliary intergrax service invoking injected adapter outside ModelCallRuntimeEvidenceAdapter PRIMARY seam',
        canonical_owner='Intergrax auxiliary module',
        canonical_contract='module-local LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/rag/contextual/chunk_enricher.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Auxiliary intergrax service invoking injected adapter outside ModelCallRuntimeEvidenceAdapter PRIMARY seam',
        canonical_owner='Intergrax auxiliary module',
        canonical_contract='module-local LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/rag/graph/indexer/community_report_graph_indexer.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Auxiliary intergrax service invoking injected adapter outside ModelCallRuntimeEvidenceAdapter PRIMARY seam',
        canonical_owner='Intergrax auxiliary module',
        canonical_contract='module-local LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/rag/graph/indexer/llm_graph_indexer.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Auxiliary intergrax service invoking injected adapter outside ModelCallRuntimeEvidenceAdapter PRIMARY seam',
        canonical_owner='Intergrax auxiliary module',
        canonical_contract='module-local LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/rag/query/query_expander.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Auxiliary intergrax service invoking injected adapter outside ModelCallRuntimeEvidenceAdapter PRIMARY seam',
        canonical_owner='Intergrax auxiliary module',
        canonical_contract='module-local LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/rag/retrieval/query_refiner.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Auxiliary intergrax service invoking injected adapter outside ModelCallRuntimeEvidenceAdapter PRIMARY seam',
        canonical_owner='Intergrax auxiliary module',
        canonical_contract='module-local LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/rag/routing/llm_tier_classifier.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Auxiliary intergrax service invoking injected adapter outside ModelCallRuntimeEvidenceAdapter PRIMARY seam',
        canonical_owner='Intergrax auxiliary module',
        canonical_contract='module-local LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/runtime/execution/inference.py',
        method='generate_structured',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Auxiliary intergrax service invoking injected adapter outside ModelCallRuntimeEvidenceAdapter PRIMARY seam',
        canonical_owner='Intergrax auxiliary module',
        canonical_contract='module-local LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/runtime/llm/model_call_runtime_evidence_adapter.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.CANONICAL_PRIMARY,
        semantic_reason='Sanctioned P4 primary outbound model invocation seam',
        canonical_owner='Runtime LLM attribution',
        canonical_contract='ModelCallRuntimeEvidenceAdapter',
        evidence_nodeid='test_trace_x_p4_model_context_attribution.py::test_txp4_q12_primary_context_model_e2e_attribution',
    ),
    RegisteredModelCallSurface(
        path='intergrax/runtime/llm/model_call_runtime_evidence_adapter.py',
        method='generate_structured',
        classification=ModelCallSurfaceClassification.CANONICAL_PRIMARY,
        semantic_reason='Sanctioned P4 primary outbound model invocation seam',
        canonical_owner='Runtime LLM attribution',
        canonical_contract='ModelCallRuntimeEvidenceAdapter',
        evidence_nodeid='test_trace_x_p4_model_context_attribution.py::test_txp4_q12_primary_context_model_e2e_attribution',
    ),
    RegisteredModelCallSurface(
        path='intergrax/runtime/llm/model_call_runtime_evidence_adapter.py',
        method='generate_with_tools',
        classification=ModelCallSurfaceClassification.CANONICAL_PRIMARY,
        semantic_reason='Sanctioned P4 primary outbound model invocation seam',
        canonical_owner='Runtime LLM attribution',
        canonical_contract='ModelCallRuntimeEvidenceAdapter',
        evidence_nodeid='test_trace_x_p4_model_context_attribution.py::test_txp4_q12_primary_context_model_e2e_attribution',
    ),
    RegisteredModelCallSurface(
        path='intergrax/runtime/llm/model_call_runtime_evidence_adapter.py',
        method='stream_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Auxiliary intergrax service invoking injected adapter outside ModelCallRuntimeEvidenceAdapter PRIMARY seam',
        canonical_owner='Intergrax auxiliary module',
        canonical_contract='module-local LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_model_context_attribution.py::test_txp4r1_q25_streaming_not_production_primary',
    ),
    RegisteredModelCallSurface(
        path='intergrax/runtime/llm/model_call_runtime_evidence_adapter.py',
        method='stream_with_tools',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Auxiliary intergrax service invoking injected adapter outside ModelCallRuntimeEvidenceAdapter PRIMARY seam',
        canonical_owner='Intergrax auxiliary module',
        canonical_contract='module-local LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_model_context_attribution.py::test_txp4r1_q25_streaming_not_production_primary',
    ),
    RegisteredModelCallSurface(
        path='intergrax/runtime/nexus/llm_task_classifier.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Auxiliary intergrax service invoking injected adapter outside ModelCallRuntimeEvidenceAdapter PRIMARY seam',
        canonical_owner='Intergrax auxiliary module',
        canonical_contract='module-local LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/runtime/nexus/planning/nexus_plan_bridge.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Auxiliary intergrax service invoking injected adapter outside ModelCallRuntimeEvidenceAdapter PRIMARY seam',
        canonical_owner='Intergrax auxiliary module',
        canonical_contract='module-local LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/runtime/nexus/tools/tool_planning_service.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Auxiliary intergrax service invoking injected adapter outside ModelCallRuntimeEvidenceAdapter PRIMARY seam',
        canonical_owner='Intergrax auxiliary module',
        canonical_contract='module-local LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/runtime/nexus/tools/tool_planning_service.py',
        method='generate_with_tools',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Auxiliary intergrax service invoking injected adapter outside ModelCallRuntimeEvidenceAdapter PRIMARY seam',
        canonical_owner='Intergrax auxiliary module',
        canonical_contract='module-local LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/runtime/organization/organization_profile_instructions_service.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Auxiliary intergrax service invoking injected adapter outside ModelCallRuntimeEvidenceAdapter PRIMARY seam',
        canonical_owner='Intergrax auxiliary module',
        canonical_contract='module-local LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/runtime/token_optimization/llm_router.py',
        method='generate_structured',
        classification=ModelCallSurfaceClassification.CANONICAL_INTERNAL_OPTIMIZATION,
        semantic_reason='Internal optimization scope; explicit non-PRIMARY classification',
        canonical_owner='Token optimization router',
        canonical_contract='token_optimization LLM router',
        evidence_nodeid='test_trace_x_p4_model_context_attribution.py::test_txp4_q16_internal_optimization_scope',
    ),
    RegisteredModelCallSurface(
        path='intergrax/runtime/user_profile/user_profile_instructions_service.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Auxiliary intergrax service invoking injected adapter outside ModelCallRuntimeEvidenceAdapter PRIMARY seam',
        canonical_owner='Intergrax auxiliary module',
        canonical_contract='module-local LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/supervisor/supervisor.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Auxiliary intergrax service invoking injected adapter outside ModelCallRuntimeEvidenceAdapter PRIMARY seam',
        canonical_owner='Intergrax auxiliary module',
        canonical_contract='module-local LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/tools/providers/eval/judge.py',
        method='generate_structured',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Auxiliary intergrax service invoking injected adapter outside ModelCallRuntimeEvidenceAdapter PRIMARY seam',
        canonical_owner='Intergrax auxiliary module',
        canonical_contract='module-local LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/websearch/service/websearch_answerer.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Auxiliary intergrax service invoking injected adapter outside ModelCallRuntimeEvidenceAdapter PRIMARY seam',
        canonical_owner='Intergrax auxiliary module',
        canonical_contract='module-local LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
    RegisteredModelCallSurface(
        path='intergrax/websearch/service/websearch_context_generator.py',
        method='generate_messages',
        classification=ModelCallSurfaceClassification.NON_PRODUCTION,
        semantic_reason='Auxiliary intergrax service invoking injected adapter outside ModelCallRuntimeEvidenceAdapter PRIMARY seam',
        canonical_owner='Intergrax auxiliary module',
        canonical_contract='module-local LLMAdapter consumer',
        evidence_nodeid='test_trace_x_p4_r3_closed_world.py::test_txp4r3_q02_model_call_surfaces_closed_world_classified',
    ),
)
