# © Artur Czarnecki. All rights reserved.

"""TRACE-X-P3-R1 qualification entry — imports mechanical gate module."""

from tests.qualification.trace_x import _trace_x_p3_r1_qualification_tests as _gates

# Re-export tests for pytest collection.
test_txp3r1_q01_start_head_provenance = _gates.test_txp3r1_q01_start_head_provenance
test_txp3r1_q02_scope_trc_04_06_only = _gates.test_txp3r1_q02_scope_trc_04_06_only
test_txp3r1_q03_v1_boundary_unchanged = _gates.test_txp3r1_q03_v1_boundary_unchanged
test_txp3r1_q04_v1_canonical_bytes_stable = _gates.test_txp3r1_q04_v1_canonical_bytes_stable
test_txp3r1_q05_v2_boundary_schema_exists = _gates.test_txp3r1_q05_v2_boundary_schema_exists
test_txp3r1_q06_v2_typed_execution_identity = _gates.test_txp3r1_q06_v2_typed_execution_identity
test_txp3r1_q08_no_host_exec_uuid_fallback = _gates.test_txp3r1_q08_no_host_exec_uuid_fallback
test_txp3r1_q10_ger_v2_carries_attempt_id = _gates.test_txp3r1_q10_ger_v2_carries_attempt_id
test_txp3r1_q21_v1_receipt_still_verifiable = _gates.test_txp3r1_q21_v1_receipt_still_verifiable
test_txp3r1_q22_v2_receipt_schema_exists = _gates.test_txp3r1_q22_v2_receipt_schema_exists
test_txp3r1_q23_v2_receipt_event_pair_valid = _gates.test_txp3r1_q23_v2_receipt_event_pair_valid
test_txp3r1_q24_cross_version_pair_rejected = _gates.test_txp3r1_q24_cross_version_pair_rejected
test_txp3r1_q25_v2_attestation_schema_id = _gates.test_txp3r1_q25_v2_attestation_schema_id
test_txp3r1_q26_persisted_event_parser_versioned = _gates.test_txp3r1_q26_persisted_event_parser_versioned
test_txp3r1_q33_strong_typing_no_any_on_v2_identity = _gates.test_txp3r1_q33_strong_typing_no_any_on_v2_identity
test_txp3r1r1q1_q01_production_delta_zero = _gates.test_txp3r1r1q1_q01_production_delta_zero
test_txp3r1r1_q1_q1_start_head_provenance = _gates.test_txp3r1r1_q1_q1_start_head_provenance
test_txp3r1r1_q2_q2_start_head_provenance = _gates.test_txp3r1r1_q2_q2_start_head_provenance
test_txp3r1r1_q3_q3_start_head_provenance = _gates.test_txp3r1r1_q3_q3_start_head_provenance
test_txp3r1r1_q3_evidence_persist_blocker_resolved = (
    _gates.test_txp3r1r1_q3_evidence_persist_blocker_resolved
)
test_txp3r1r1_gate_registry_mechanical_integrity = _gates.test_txp3r1r1_gate_registry_mechanical_integrity
test_txp3r1r1_closed_world_inventory_classified = _gates.test_txp3r1r1_closed_world_inventory_classified
test_txp3r1r1_q01_r1_start_head_ancestry = _gates.test_txp3r1r1_q01_r1_start_head_ancestry
test_txp3r1r1_q10_ger_v2_tenant_mandatory = _gates.test_txp3r1r1_q10_ger_v2_tenant_mandatory
test_txp3r1r1_q11_ger_proof_tenant_exact_equality_ok = _gates.test_txp3r1r1_q11_ger_proof_tenant_exact_equality_ok
test_txp3r1r1_q12_proof_tenant_absence_rejected = _gates.test_txp3r1r1_q12_proof_tenant_absence_rejected
test_txp3r1r1_q13_ebe_v2_tenant_mandatory = _gates.test_txp3r1r1_q13_ebe_v2_tenant_mandatory
test_txp3r1r1_q14_ebe_tenant_copied_from_ger = _gates.test_txp3r1r1_q14_ebe_tenant_copied_from_ger
test_txp3r1r1_q15_receipt_preserves_tenant = _gates.test_txp3r1r1_q15_receipt_preserves_tenant
test_txp3r1r1_q23_atomic_provider_execution_attribution_in_ebe_v2 = _gates.test_txp3r1r1_q23_atomic_provider_execution_attribution_in_ebe_v2
test_txp3r1r1_q21_reliability_projection_non_authoritative = _gates.test_txp3r1r1_q21_reliability_projection_non_authoritative
test_txp3r1r1_q25_governance_not_execution = _gates.test_txp3r1r1_q25_governance_not_execution
test_txp3r1r1_q28_no_heuristic_provider_join = _gates.test_txp3r1r1_q28_no_heuristic_provider_join
test_txp3r1r1_q26_exactly_one_compose_owner = _gates.test_txp3r1r1_q26_exactly_one_compose_owner
test_txp3r1r1_q29_frz_trc_04_readiness_evidence = _gates.test_txp3r1r1_q29_frz_trc_04_readiness_evidence
test_txp3r1r1_q30_frz_trc_06_readiness_evidence = _gates.test_txp3r1r1_q30_frz_trc_06_readiness_evidence
test_txp3r1r1_pass1_mechanical_nodeid_manifest = _gates.test_txp3r1r1_pass1_mechanical_nodeid_manifest
test_txp3r1r1_tenant_isolation_audit_complete = _gates.test_txp3r1r1_tenant_isolation_audit_complete
