# © Artur Czarnecki. All rights reserved.

"""TRACE-X-P3-R1 qualification entry — imports mechanical gate module."""

from tests.qualification.trace_x import _trace_x_p3_r1_qualification_tests as _gates

# Re-export tests for pytest collection.
test_txp3r1_q01_start_head_provenance = _gates.test_txp3r1_q01_start_head_provenance
test_txp3r1_q02_scope_trc_04_06_only = _gates.test_txp3r1_q02_scope_trc_04_06_only
test_txp3r1_q03_v1_boundary_unchanged = _gates.test_txp3r1_q03_v1_boundary_unchanged
test_txp3r1_q04_v1_canonical_bytes_stable = _gates.test_txp3r1_q04_v1_canonical_bytes_stable
test_txp3r1_q05_v2_boundary_schema_exists = _gates.test_txp3r1_q05_v2_boundary_schema_exists
test_txp3r1_q06_v2_typed_execution_identity = _gates.test_txp3r1_q06_v2_typed_execution_identity
test_txp3r1_q08_no_host_exec_uuid_fallback = _gates.test_txp3r1_q08_no_host_exec_uuid_fallback
test_txp3r1_q10_ger_v2_carries_attempt_id = _gates.test_txp3r1_q10_ger_v2_carries_attempt_id
test_txp3r1_q21_v1_receipt_still_verifiable = _gates.test_txp3r1_q21_v1_receipt_still_verifiable
test_txp3r1_q22_v2_receipt_schema_exists = _gates.test_txp3r1_q22_v2_receipt_schema_exists
test_txp3r1_q23_v2_receipt_event_pair_valid = _gates.test_txp3r1_q23_v2_receipt_event_pair_valid
test_txp3r1_q24_cross_version_pair_rejected = _gates.test_txp3r1_q24_cross_version_pair_rejected
test_txp3r1_q25_v2_attestation_schema_id = _gates.test_txp3r1_q25_v2_attestation_schema_id
test_txp3r1_q26_persisted_event_parser_versioned = _gates.test_txp3r1_q26_persisted_event_parser_versioned
test_txp3r1_q33_strong_typing_no_any_on_v2_identity = _gates.test_txp3r1_q33_strong_typing_no_any_on_v2_identity
test_txp3r1_enterprise_audit_matrix_all_pass = _gates.test_txp3r1_enterprise_audit_matrix_all_pass
